export const doctoralReviewedAt = "2026-08-16";

export type DoctoralSource = {
  id: string;
  title: string;
  jurisdiction: string;
  type: "Legislation" | "Court rules" | "Judgment" | "Official guidance" | "Treaty";
  url: string;
  proposition: string;
};

export type Dossier = {
  slug: string;
  number: string;
  title: string;
  subtitle: string;
  question: string;
  thesis: string;
  jurisdictions: { name: string; rule: string; consequence: string; bridge: string }[];
  sections: { heading: string; paragraphs: string[] }[];
  chain: { label: string; finding: string }[];
  conclusion: string;
  sourceIds: string[];
  furtherQuestions: string[];
};

export const doctoralSources: DoctoralSource[] = [
  { id: "ew-cpr6", title: "Civil Procedure Rules, Part 6", jurisdiction: "England & Wales", type: "Court rules", url: "https://www.justice.gov.uk/courts/procedure-rules/civil/rules/part06", proposition: "Methods, deemed service, default addresses, alternative service and service out." },
  { id: "ew-pd6a", title: "Practice Direction 6A", jurisdiction: "England & Wales", type: "Court rules", url: "https://www.justice.gov.uk/courts/procedure-rules/civil/rules/part06/pd_part06a", proposition: "Operational detail for personal and alternative service." },
  { id: "abela", title: "Abela v Baadarani [2013] UKSC 44", jurisdiction: "United Kingdom", type: "Judgment", url: "https://www.supremecourt.uk/cases/uksc-2012-0023", proposition: "Alternative service is directed to bringing the claim form to the defendant's attention; service remains a formal procedural act." },
  { id: "barton", title: "Barton v Wright Hassall LLP [2018] UKSC 12", jurisdiction: "United Kingdom", type: "Judgment", url: "https://www.supremecourt.uk/cases/uksc-2016-0136", proposition: "Actual knowledge does not, without more, cure non-compliance with the service rules." },
  { id: "cameron", title: "Cameron v Liverpool Victoria Insurance [2019] UKSC 6", jurisdiction: "United Kingdom", type: "Judgment", url: "https://www.supremecourt.uk/cases/uksc-2017-0115", proposition: "An anonymous defendant must be capable of identification and service; an unidentifiable absconder cannot simply be served through an insurer." },
  { id: "iom-hc", title: "Rules of the High Court of Justice 2009", jurisdiction: "Isle of Man", type: "Court rules", url: "https://legislation.gov.im/cms/images/LEGISLATION/SUBORDINATE/2009/2009-0352/2009-0352_11.pdf", proposition: "The Manx procedural code supplies its own routes for personal, alternative and out-of-jurisdiction service." },
  { id: "ie-o9", title: "Rules of the Superior Courts, Order 9", jurisdiction: "Ireland", type: "Court rules", url: "https://www.courts.ie/court-rules/full-court-rule?url=Order-9-Superior-Service-of-summons", proposition: "Originating summons service, including personal service, registered post, company service and substituted service." },
  { id: "ie-o121", title: "Rules of the Superior Courts, Order 121", jurisdiction: "Ireland", type: "Court rules", url: "https://www.courts.ie/court-rules/full-court-rule?url=Order-121-Superior-Service-of-Documents", proposition: "Service of documents after commencement and the filing fallback where no service address is supplied." },
  { id: "ie-service", title: "Serving and proof of service (civil)", jurisdiction: "Ireland", type: "Official guidance", url: "https://www.courts.ie/guides/serving-and-proof-of-service-%28civil%29", proposition: "Official guide to post, personal and substituted service and proof." },
  { id: "uk-plates", title: "Displaying number plates", jurisdiction: "Great Britain", type: "Official guidance", url: "https://www.gov.uk/displaying-number-plates", proposition: "A registration mark must be displayed correctly and may not be rearranged." },
  { id: "uk-import", title: "Temporary imports of vehicles", jurisdiction: "United Kingdom", type: "Official guidance", url: "https://www.gov.uk/importing-vehicles-into-the-uk/temporary-imports", proposition: "A visitor may normally use a foreign-registered vehicle temporarily if the vehicle remains registered and taxed at home and the visitor is not UK-resident." },
  { id: "iom-vehicle-regs", title: "Licensing and Registration of Vehicles Regulations 2015", jurisdiction: "Isle of Man", type: "Legislation", url: "https://legislation.gov.im/cms/images/LEGISLATION/SUBORDINATE/2015/2015-0355/2015-0355_1.pdf", proposition: "The Manx registry assigns MAN, MN and MANX marks and regulates assignment and reassignment." },
  { id: "iom-vehicle-act", title: "Licensing and Registration of Vehicles Act 1985", jurisdiction: "Isle of Man", type: "Legislation", url: "https://legislation.gov.im/cms/images/LEGISLATION/PRINCIPAL/1985/1985-0021/1985-0021.pdf", proposition: "Registration and proper display are domestic statutory obligations." },
  { id: "iom-visitors", title: "Vehicle registration and licensing", jurisdiction: "Isle of Man", type: "Official guidance", url: "https://www.gov.im/categories/travel-traffic-and-motoring/drivers-and-vehicles/vehicle-registration-and-licensing", proposition: "Official Manx visitor and re-registration guidance." },
  { id: "jersey-marks", title: "Jersey registration numbers", jurisdiction: "Jersey", type: "Official guidance", url: "https://www.gov.je/Travel/Motoring/BuyingSellingVehicle/pages/registrationnumbers.aspx", proposition: "Jersey numbers are allocated locally; the right to display can be transferred while the number remains government property." },
  { id: "uk-ca", title: "Companies Act 2006", jurisdiction: "United Kingdom", type: "Legislation", url: "https://www.legislation.gov.uk/ukpga/2006/46/contents", proposition: "Part 5 controls UK company names; Part 6 regulates registered offices; section 1139 provides a statutory company-service route." },
  { id: "uk-names", title: "Incorporation and names", jurisdiction: "United Kingdom", type: "Official guidance", url: "https://www.gov.uk/government/publications/incorporation-and-names/incorporation-and-names", proposition: "Current Companies House rules on same-as, too-like, sensitive and opportunistic names." },
  { id: "uk-cnt", title: "Company Names Tribunal defended decisions", jurisdiction: "United Kingdom", type: "Judgment", url: "https://www.gov.uk/government/publications/company-names-tribunal-defended-decisions-and-orders", proposition: "Official decisional archive for objections under Companies Act 2006 section 69." },
  { id: "iom-ca", title: "Companies Act 2006 (Isle of Man)", jurisdiction: "Isle of Man", type: "Legislation", url: "https://legislation.gov.im/cms/images/LEGISLATION/PRINCIPAL/2006/2006-0013/2006-0013.pdf", proposition: "Independent Manx incorporation, naming, legal personality, registered-agent and registered-office rules." },
  { id: "iom-names", title: "Companies Registry: check name availability", jurisdiction: "Isle of Man", type: "Official guidance", url: "https://services.gov.im/companies-registry/", proposition: "A proposed name is tested for uniqueness, distinctiveness and similarity within the Manx register." },
  { id: "ie-ca", title: "Companies Act 2014", jurisdiction: "Ireland", type: "Legislation", url: "https://www.irishstatutebook.ie/eli/2014/act/38/", proposition: "Irish company naming, reservation, registered-office and service rules." },
  { id: "ie-cro-name", title: "Company name registration", jurisdiction: "Ireland", type: "Official guidance", url: "https://cro.ie/Registration/Company/Incidental-Obligations/Company-Name/", proposition: "CRO guidance on availability, distinction and reservation under sections 28 and 29." },
  { id: "jersey-companies", title: "Companies (Jersey) Law 1991", jurisdiction: "Jersey", type: "Legislation", url: "https://jerseylaw.je/laws/current/l_30_1991", proposition: "Articles 13–15 regulate names; Articles 67 and 72 regulate registered offices and service." },
  { id: "iom-rec-act", title: "Judgments (Reciprocal Enforcement) (Isle of Man) Act 1968", jurisdiction: "Isle of Man", type: "Legislation", url: "https://legislation.gov.im/cms/legislation/index/by-subject.html", proposition: "Domestic statutory foundation for registration of designated foreign judgments." },
  { id: "iom-rec-order", title: "Judgments (Reciprocal Enforcement) (United Kingdom and Channel Islands) Order 2011", jurisdiction: "Isle of Man", type: "Legislation", url: "https://legislation.gov.im/cms/images/LEGISLATION/SUBORDINATE/2011/2011-0930/2011-0930_1.pdf", proposition: "Extends the Manx 1968 Act to specified UK and Channel Islands courts." },
  { id: "jersey-rec", title: "Judgments (Reciprocal Enforcement) (Jersey) Law 1960", jurisdiction: "Jersey", type: "Legislation", url: "https://www.jerseylaw.je/laws/current/l_14_1960", proposition: "Registration, jurisdictional filters, defences, public policy and general recognition in Jersey." },
  { id: "hague2019", title: "2019 Judgments Convention", jurisdiction: "International", type: "Treaty", url: "https://www.hcch.net/en/instruments/conventions/full-text/?cid=137", proposition: "Common recognition and enforcement rules for in-scope civil and commercial judgments." },
  { id: "uk-hague", title: "Hague 2019 enters into force for the UK", jurisdiction: "United Kingdom", type: "Official guidance", url: "https://www.gov.uk/government/speeches/statement-on-the-entry-into-force-of-the-2019-hague-convention", proposition: "The Convention entered into force for the UK on 1 July 2025." },
  { id: "ie-hague", title: "The Hague Conventions", jurisdiction: "Ireland", type: "Official guidance", url: "https://www.gov.ie/en/department-of-foreign-affairs/publications/the-hague-conventions/", proposition: "Ireland is bound through the EU; Hague 2019 entered into force there on 1 September 2023." },
  { id: "ew-part74", title: "Civil Procedure Rules, Part 74", jurisdiction: "England & Wales", type: "Court rules", url: "https://www.justice.gov.uk/courts/procedure-rules/civil/rules/part74", proposition: "Procedure for recognition and enforcement under the 1920, 1933 and 1982 Acts and Hague 2005/2019." },
  { id: "crown-status", title: "Crown Dependencies: constitutional factsheet", jurisdiction: "United Kingdom / Crown Dependencies", type: "Official guidance", url: "https://www.gov.uk/government/publications/crown-dependencies-jersey-guernsey-and-the-isle-of-man", proposition: "The Crown Dependencies are not part of the UK and possess their own legislatures, courts and legal systems." },
];

export const doctoralDossiers: Dossier[] = [
  {
    slug: "service-of-process",
    number: "01",
    title: "Service is not mere notice",
    subtitle: "Addresses, absent defendants and the limits of procedural equivalence",
    question: "When is originating process validly served in England & Wales, the Isle of Man and Ireland—and what survives when the judgment crosses a border?",
    thesis: "All three systems pursue notice, but none reduces service to factual awareness. Each domestic code defines its own valid methods, addresses, evidence and judicial dispensations. A later enforcing court therefore asks two different questions: whether the origin court's law treated service as valid, and whether recognition law permits enforcement against a defendant who did not appear.",
    jurisdictions: [
      { name: "England & Wales", rule: "CPR Part 6 separates methods, deemed dates, default addresses and service out. Rule 6.9 uses a usual or last-known residence for an individual where no address has been supplied; rules 6.15 and 6.27 enable court-controlled alternatives.", consequence: "Knowledge alone is not a universal cure. Barton demonstrates the discipline of the rules; Abela explains the purpose of alternative service without dissolving formality.", bridge: "At enforcement, CPR Part 74 and any applicable treaty or statute govern recognition; service becomes a due-process filter, not a passport issued by CPR Part 6." },
      { name: "Isle of Man", rule: "The Rules of the High Court of Justice 2009 are an autonomous Manx procedural code. Personal service, permitted-address service, alternative service and service outside the Island derive from that code—not from the English CPR as such.", consequence: "English materials may be persuasive where language and principle overlap, but they do not substitute for the Manx rule text or a Manx order.", bridge: "The 1968 Act and 2011 Order create a registration bridge for designated UK and Channel Islands judgments, subject to statutory safeguards." },
      { name: "Ireland", rule: "Order 9 governs originating summonses. It permits personal service and, in defined circumstances, registered post to a last-known residence or place of business in the State with proof of delivery; company service follows Companies Act 2014 section 51. Orders 9 and 121 supply substituted-service routes.", consequence: "A person with no stable home is not legally invisible, but the claimant ordinarily needs evidence and a court-controlled alternative rather than a self-created 'service address'.", bridge: "For proceedings begun from 1 July 2025, Hague 2019 can connect in-scope UK and Irish civil or commercial judgments; exclusions and refusal grounds still matter." },
    ],
    sections: [
      { heading: "Characterisation before comparison", paragraphs: ["The phrase ‘service address’ hides several institutions. A claimant's address for service, a defendant's default residential address, a company's registered office and an address selected in a contract perform different legal functions. The comparative error is to treat them as interchangeable simply because the same building can sometimes satisfy more than one rule.", "The correct sequence is to identify the document, the defendant's legal character, the forum, whether the defendant is inside the jurisdiction, and the rule authorising the chosen method. Only then can one ask whether actual receipt, deemed receipt or a judicial order completes service."] },
      { heading: "The addressless individual", paragraphs: ["None of the three systems grants a natural person a general power to manufacture a permanent procedural identity by declaring an arbitrary mailbox. Instead, the systems use last-known residence or business, personal delivery, service through an authorised lawyer in the proceedings, service out, or a court-approved substitute. The claimant must show diligence and a rational connection between the proposed method and likely notice.", "Cameron exposes the limiting case. Describing a defendant is possible where the description identifies who falls inside and outside the class; it does not make service possible on an individual who is both unnamed and unidentifiable. The problem is not homelessness as such. It is the absence of a legally authorised route capable of connecting process to the defendant."] },
      { heading: "Recognition is a second inquiry", paragraphs: ["Valid service in the origin does not compel every neighbouring court to enforce. Registration statutes and Hague instruments examine the jurisdiction of the origin court and protect a non-appearing defendant who was not notified in sufficient time and manner to defend. Thus domestic validity is relevant evidence, but it is not the whole recognition test.", "This distinction also prevents a reverse mistake: a minor difference between domestic service codes does not automatically make a foreign judgment unenforceable. The enforcing court applies its recognition regime, including its particular notice standard and public-policy limits, rather than re-litigating the origin's procedure as if it were sitting on appeal."] },
    ],
    chain: [
      { label: "Characterise", finding: "Originating process, later document, statutory notice or enforcement notice?" },
      { label: "Locate", finding: "Inside the forum, outside it, or genuinely unlocated?" },
      { label: "Authorise", finding: "Use the forum's rule, statute or a court order—not a political analogy." },
      { label: "Prove", finding: "Record method, date, delivery evidence and any diligence supporting substitution." },
      { label: "Recognise", finding: "Apply the enforcing forum's treaty, registration statute or common-law test." },
    ],
    conclusion: "The residual gap is deliberate. The systems facilitate notice but preserve judicial control over coercive jurisdiction. A claimant may bridge uncertainty with an alternative-service order; the claimant cannot convert a convenient address into universally valid service by assertion.",
    sourceIds: ["ew-cpr6", "ew-pd6a", "abela", "barton", "cameron", "iom-hc", "ie-o9", "ie-o121", "ie-service", "ew-part74", "hague2019"],
    furtherQuestions: ["How do email and platform messaging alter the evidential—not merely formal—case for alternative service?", "Which notice failures under Hague 2019 are mandatory and which discretionary grounds for refusal?", "Does a contractual process-agent clause survive assignment or insolvency?", "How should procedural law account for homelessness without constructing a second-class notice regime?"],
  },
  {
    slug: "vehicle-registration-marks",
    number: "02",
    title: "A mark travels with a legal system",
    subtitle: "Personalised identifiers, visiting vehicles and territorial re-registration",
    question: "Can a Manx or Jersey registration mark be lawfully displayed in Great Britain, and when does a visiting vehicle become a domestic vehicle?",
    thesis: "Uniqueness is registry-relative. A lawfully assigned Manx or Jersey mark remains evidence of registration in its home system; it does not become a DVLA mark. Great Britain accepts it during lawful temporary use of the foreign-registered vehicle, but residence, duration, taxation and import status can trigger an independent duty to register in Britain.",
    jurisdictions: [
      { name: "Great Britain", rule: "DVLA controls GB registration and plate display. A visitor can normally use a vehicle bearing its home registration temporarily if the vehicle is registered and taxed at home and the user is not UK-resident, usually for up to six months in a twelve-month period.", consequence: "The foreign mark is lawful because the foreign vehicle is temporarily admitted—not because the mark has been copied into or reserved on the DVLA register.", bridge: "Temporary-import rules and international road-traffic practice supply conditional recognition; UK registration obligations end it." },
      { name: "Isle of Man", rule: "The 2015 Regulations allocate MAN, MN and MANX series and permit assignment or reassignment under Manx control. The 1985 Act requires proper display on a Manx-registered vehicle.", consequence: "A purchased entitlement concerns assignment within the Manx system. It does not authorise the same characters on a different GB-registered vehicle.", bridge: "The vehicle may visit Great Britain on its Manx registration while the visitor conditions remain satisfied." },
      { name: "Jersey", rule: "Jersey administers its own J-number system. The transferable asset is a right to display, while the registration number remains government property.", consequence: "Local transfer rules do not transfer DVLA jurisdiction or extinguish British import and residence rules.", bridge: "The same temporary-use logic can recognise a Jersey-registered vehicle, subject to proof of home registration and lawful import." },
    ],
    sections: [
      { heading: "Three objects that look like one", paragraphs: ["A registration record, the assigned alphanumeric mark and the physical plate are separate legal objects. Personalisation markets encourage owners to describe a mark as property, yet the statutory system ordinarily grants a regulated entitlement to assign or display rather than ownership of characters everywhere.", "That distinction resolves the apparent collision of identical marks. Two registries can lawfully assign similar characters because each identifies a vehicle within a different register. The road user and enforcement authority read the plate together with territorial format and vehicle documentation."] },
      { heading: "Movement does not merge registries", paragraphs: ["When a Manx vehicle boards a ferry to Great Britain, the legal event is temporary cross-border use of a foreign-registered vehicle. The Manx registration remains the source of the mark; British law supplies the conditions for use on British roads. If those conditions fail—most importantly because the keeper becomes resident or the permitted period expires—the problem becomes non-registration or import non-compliance, not retroactive invalidity of the Manx allocation.", "A mark therefore cannot be detached from the vehicle and displayed as decoration on a GB vehicle where it purports to be that vehicle's registration. Correct display rules protect the link between the visible identifier and the authoritative record."] },
      { heading: "Administrative recognition as a narrow bridge", paragraphs: ["This field is not primarily a judgments-recognition problem. It is administrative comity implemented through traffic, tax, customs and registration rules. The bridge recognises status for a limited purpose and time. It does not naturalise the foreign registration into the host registry.", "The policy compromise serves mobility while preventing durable avoidance of the fiscal, safety and traceability rules attached to residence. Its critical weakness is informational: guidance is often clearer than the scattered legislative chain, so users may mistake an accessible six-month summary for the whole legal test."] },
    ],
    chain: [
      { label: "Allocate", finding: "The home registry assigns a unique mark within its own dataset." },
      { label: "Attach", finding: "The mark identifies the particular vehicle under home law." },
      { label: "Enter", finding: "Host import and visitor rules permit conditional temporary use." },
      { label: "Display", finding: "Plates must remain legible, correctly formed and attached to that vehicle." },
      { label: "Re-register", finding: "Residence, duration or import status can require a new host registration." },
    ],
    conclusion: "A Manx or Jersey mark can be displayed in Great Britain on the lawfully visiting vehicle to which it belongs. The same mark cannot simply be transplanted onto a GB vehicle. The legal bridge recognises the vehicle's temporary foreign status, not an abstract proprietary claim to the characters.",
    sourceIds: ["uk-plates", "uk-import", "iom-vehicle-regs", "iom-vehicle-act", "iom-visitors", "jersey-marks"],
    furtherQuestions: ["How should automatic number-plate recognition encode jurisdiction as well as characters?", "When does student or dual residence alter temporary-import status?", "Are auctioned registration entitlements property for insolvency and succession?", "What remedy follows an erroneous administrative demand to re-register?"],
  },
  {
    slug: "company-names",
    number: "03",
    title: "One name, four registries",
    subtitle: "Corporate identity, goodwill and false equivalence across borders",
    question: "Can identical company names coexist in the UK, Isle of Man, Ireland and Jersey, and what happens when the businesses meet?",
    thesis: "Yes. Each register polices its own index under its own statute, so availability is territorial. Incorporation creates a legal person and an official name inside that system; it does not confer a universal trade monopoly. Cross-border conflict is handled, if at all, through passing off, trade marks, domestic name-objection mechanisms, fraud controls and accurate identification by company number and jurisdiction.",
    jurisdictions: [
      { name: "United Kingdom", rule: "Companies Act 2006 and current Companies House practice reject same-as names, regulate too-like and sensitive names, and permit objections to opportunistic registrations through the Company Names Tribunal.", consequence: "The index test and the section 69 goodwill remedy are distinct. A name can pass incorporation screening yet remain vulnerable to trade mark infringement or passing off.", bridge: "UK goodwill, trade marks and misleading-connection rules can reach conduct involving a foreign company, but foreign incorporation alone does not reserve the UK register." },
      { name: "Isle of Man", rule: "Manx Acts and Registry practice require a name acceptable and sufficiently distinctive within the Manx system; a 2006 Act company is a separate Manx legal person with a registered agent and office.", consequence: "A UK consent or reservation is evidentially useful but not determinative of Manx availability.", bridge: "UK registered trade marks extend to the Isle of Man; unregistered goodwill and local company law still require their own analysis." },
      { name: "Ireland", rule: "Companies Act 2014 sections 26–29 and CRO practice govern names and reservations. Ireland's register is not a regional branch of Companies House.", consequence: "An identical UK name can therefore coexist unless Irish rules or other rights prevent it. Documents must identify the correct Irish or foreign legal person.", bridge: "EU and Irish trade mark law, passing off and recognition of foreign companies address market conduct, not global name exclusivity." },
      { name: "Jersey", rule: "Companies (Jersey) Law 1991 Article 13 permits the registrar to refuse a misleading or undesirable name; Article 15 permits a direction to change one.", consequence: "The Jersey test is locally administered and does not automatically search or bind the other three registers.", bridge: "Market-facing misconduct may engage separate intellectual-property, fraud or passing-off rules; registry coexistence itself is not wrongdoing." },
    ],
    sections: [
      { heading: "Registry truth and market truth", paragraphs: ["A companies register answers: which legal person does this jurisdiction constitute or record under this name? Passing off asks a different question: has the defendant misrepresented its business in a way likely to damage the claimant's goodwill? Trade mark law asks about protected signs in specified territories and classes. Treating these as one ‘name right’ produces both over- and under-protection.", "The UK Company Names Tribunal adds a targeted anti-opportunism remedy. Its decisions show that the statutory inquiry is not a general substitute for passing off. This modular design matters comparatively because Ireland, the Isle of Man and Jersey need not copy the same institutional remedy to police deception through their own law."] },
      { heading: "Simultaneous identity without shared personality", paragraphs: ["Four companies called Meridian Harbour Limited could, in principle, exist in four registries. They remain four persons. The decisive identifiers are jurisdiction, company number, registered office and—where relevant—register entry. A contract or claim form that uses the name alone risks factual ambiguity, but the error is not solved by assuming the oldest incorporation owns the name everywhere.", "Change-of-name provisions commonly preserve the entity's rights, obligations and proceedings. This confirms that the corporation is not ontologically identical to its label: the legal person continues while the label changes."] },
      { heading: "Critical account: administrative borders and private power", paragraphs: ["Territorial registers lower entry costs by limiting the search universe, but they externalise some conflict to businesses and consumers. Well-resourced firms can layer trade marks, monitoring and litigation across jurisdictions; smaller firms may discover coexistence only after confusion occurs.", "The proper reform question is not whether to create one British-Irish name register. It is whether interoperable warnings, jurisdiction-qualified search results and machine-readable entity identifiers can reduce confusion without implying constitutional hierarchy or granting incumbents excessive control over language."] },
    ],
    chain: [
      { label: "Search", finding: "Test availability separately in each target registry." },
      { label: "Incorporate", finding: "The certificate creates or records a person under local law." },
      { label: "Identify", finding: "Use name, number, jurisdiction and registered office together." },
      { label: "Trade", finding: "Assess trade marks, goodwill, misrepresentation and consumer confusion." },
      { label: "Remedy", finding: "Choose the registry objection, IP claim, passing off or fraud route that fits." },
    ],
    conclusion: "Identical names can lawfully coexist because the registers answer territorial questions. Conflict begins not with coexistence but with misleading conduct, protected rights or defective identification. The intellectual discipline is to keep incorporation, naming, personality and market reputation analytically separate.",
    sourceIds: ["uk-ca", "uk-names", "uk-cnt", "iom-ca", "iom-names", "ie-ca", "ie-cro-name", "jersey-companies", "crown-status"],
    furtherQuestions: ["Should registry search interfaces disclose close matches in neighbouring jurisdictions?", "Which law governs passing off where a website targets several islands?", "Can a company-number-first citation standard reduce mistaken-identity litigation?", "How do beneficial-ownership transparency reforms alter the politics of corporate naming?"],
  },
  {
    slug: "registered-offices-and-individuals",
    number: "04",
    title: "The office is not the person",
    subtitle: "Corporate publicity, private residence and addresslessness",
    question: "Why can a company be required to maintain a public office while an individual without a fixed home cannot simply borrow it as a universal service point?",
    thesis: "A registered office is a statutory organ of corporate publicity and receipt. It belongs to the company, not automatically to its directors, shareholders, employees or affiliates. Service on a natural person at that address requires an independent rule, appointment or court order. This asymmetry reflects legal personality and disclosure policy rather than a drafting accident.",
    jurisdictions: [
      { name: "United Kingdom", rule: "Companies Act 2006 requires a registered office at an appropriate address in the company's UK jurisdiction. Statutory documents can be served on the company there; directors separately provide service addresses under the Act.", consequence: "Service on the company is not service on a director personally. The same location works for both only when each applicable rule is independently satisfied.", bridge: "A foreign company's home office may identify it, but English originating process still follows CPR Part 6 and any statutory corporate route." },
      { name: "Isle of Man", rule: "A 2006 Act company must maintain a physical registered office in the Island and a licensed registered agent. The office anchors records and statutory communications.", consequence: "The agent's corporate appointment does not make it personal agent for every beneficial owner or controller.", bridge: "Cross-border claimants must use Manx or forum service rules; group structure does not create implied universal agency." },
      { name: "Ireland", rule: "Companies Act 2014 section 50 requires a registered office in the State; section 51 authorises service on the company there. Order 9 supplies separate rules for individuals.", consequence: "A care-of office can satisfy the company's statute but cannot erase the distinction between the company and a natural defendant.", bridge: "An individual may expressly appoint a solicitor or process agent where the relevant rule or contract permits, but that is a separate juridical act." },
      { name: "Jersey", rule: "Articles 67 and 72 of the Companies (Jersey) Law 1991 make the registered office the company's local formal point of presence and service.", consequence: "The statutory fiction is entity-specific; it is not a household address for connected persons.", bridge: "Foreign service or recognition still depends on the applicable Jersey rules and any reciprocal regime." },
    ],
    sections: [
      { heading: "Why corporations have an address", paragraphs: ["A corporation lacks a body that can receive a document in the ordinary sense. The registered office converts legal abstraction into a stable public contact point. It supports inspection, regulator communication, creditor notice and service even when managers or owners move.", "Natural persons present the opposite policy problem. Law seeks effective notice while limiting unnecessary public exposure of home addresses. Rules therefore accept personal service, last-known locations and judicial substitutes rather than compelling every person to maintain a public office."] },
      { heading: "Separate personality does procedural work", paragraphs: ["The statement that a company is separate from its members is not merely an insolvency slogan. It allocates receipt of legal documents. A document addressed to Company A and delivered to its registered office engages the company's receipt rule; it does not, without more, commence a personal claim against Director B.", "Likewise, a registered agent's duties derive from statute and appointment. Courts should not infer personal agency from convenience or common control alone. Express contractual process-agent clauses can change the analysis, but their scope, governing law and continued authority must be proved."] },
      { heading: "Addresslessness and procedural equality", paragraphs: ["Last-known-address rules can disadvantage itinerant, displaced and homeless defendants because they formalise a location the person may no longer monitor. Yet dispensing with formality altogether would expose such defendants to hidden proceedings. Court-supervised substitution is the principal balancing mechanism: it asks what method is likely to give notice on the evidence available.", "A doctorate-level critique should therefore test not only formal validity but distributional effect. Who has the resources to trace, apply, translate and prove? Which digital channels are stable enough for notice? When does public advertising become symbolic rather than communicative? Those questions reveal the access-to-justice cost of apparently neutral formality."] },
    ],
    chain: [
      { label: "Entity", finding: "Identify the exact legal defendant rather than the human network around it." },
      { label: "Function", finding: "Ask whether the address is statutory office, director service address or procedural address." },
      { label: "Authority", finding: "Locate the rule that makes delivery effective for that defendant." },
      { label: "Agency", finding: "Prove any express appointment; do not infer it from affiliation." },
      { label: "Equity", finding: "Evaluate whether the method creates a fair chance to respond." },
    ],
    conclusion: "A corporate office is a deliberately bounded fiction. It stabilises service on the company precisely because it does not collapse the identities of everyone connected to it. Individuals without a fixed residence require fact-sensitive, court-controlled solutions rather than borrowed corporate formality.",
    sourceIds: ["uk-ca", "ew-cpr6", "iom-ca", "ie-ca", "ie-o9", "ie-o121", "jersey-companies", "barton", "cameron"],
    furtherQuestions: ["Should a verified digital service address become optional for individuals?", "When is a registered-office provider also an authorised process agent?", "How do privacy-protection filings affect creditor access to service information?", "Can group-wide service clauses bind later subsidiaries or directors?"],
  },
  {
    slug: "recognition-and-residual-gaps",
    number: "05",
    title: "Validity stops at the border",
    subtitle: "A chain-of-effects model for the British–Irish legal archipelago",
    question: "What exactly happens when a formally valid Manx act is relied upon in the United Kingdom or Ireland?",
    thesis: "The receiving system does not ask one question called ‘recognition’. It characterises the act, selects a connecting rule, tests the relevant bridge and preserves local mandatory rules. Political proximity supplies context, not a conflicts rule. The result can be full recognition, recognition for a limited purpose, re-registration, evidential weight only or no effect.",
    jurisdictions: [
      { name: "Isle of Man → United Kingdom", rule: "For designated money judgments, the Manx 1968 Act/2011 Order and reciprocal UK legislation create structured registration routes. Other acts—company status, vehicle registration, service—use different statutory or common-law bridges.", consequence: "There is no single ‘British family’ recognition principle. Each subject matter has its own gateway and exclusions.", bridge: "Reciprocal-judgment legislation is the clearest bridge; temporary vehicle admission and foreign-company recognition are narrower functional bridges." },
      { name: "United Kingdom ↔ Ireland", rule: "Hague 2019 has applied between the UK and EU/Ireland for in-scope judgments in proceedings commenced from 1 July 2025. Hague 2005 remains relevant to exclusive choice-of-court agreements; transitional and excluded matters use other regimes.", consequence: "The post-Brexit gap has narrowed, not disappeared. Insolvency, intellectual property, family matters and other exclusions require separate analysis.", bridge: "Treaty recognition is rule-bound and subject to eligibility, timing and refusal grounds." },
      { name: "Isle of Man → Ireland", rule: "A Manx act does not become an Irish act by constitutional association. One must identify Irish common-law recognition, a specific statute or an international instrument territorially extended to the Isle of Man.", consequence: "A UK treaty ratification ordinarily covers the UK territorial unit stated; Crown Dependencies must be expressly extended where the treaty permits.", bridge: "Evidence of valid Manx law may establish status or fact, but enforcement requires an Irish legal route." },
      { name: "Jersey / other Dependencies", rule: "Jersey's 1960 Law illustrates the reciprocal model: registration is available only for designated systems and remains subject to jurisdiction, notice, fraud and public-policy controls.", consequence: "Similarity across island statutes is not automatic reciprocity; the designating instrument matters.", bridge: "Domestic implementing law is the operative bridge." },
    ],
    sections: [
      { heading: "The six-step conflicts audit", paragraphs: ["First characterise the object: judgment, incorporation, public registration, contractual appointment, licence or procedural act. Second identify the origin law and prove what it makes valid. Third select the receiving forum's conflicts rule. Fourth locate a treaty, statute or common-law doctrine that gives effect. Fifth test territorial scope, timing and exclusions. Sixth apply local mandatory rules, procedural safeguards and public policy.", "Skipping characterisation creates false analogies. A judgment commands performance and engages due-process scrutiny; a vehicle registration establishes administrative status; a company certificate evidences personality; valid service is one fact in jurisdiction and enforcement. Each travels differently."] },
      { heading: "Hague 2019 changes the contemporary map", paragraphs: ["The UK entered Hague 2019 on 1 July 2025, while Ireland is bound through the EU from 1 September 2023. Between them, the Convention now supplies a major bridge for qualifying civil and commercial judgments where proceedings began on or after the Convention operated between the states. CPR Part 74 implements the incoming route in England and Wales.", "The Convention is not universal. Its subject exclusions, eligibility filters, timing rule and refusal grounds preserve residual space. Nor should UK participation be assumed to include the Isle of Man: Crown Dependencies are constitutionally separate and treaty extension is a distinct act."] },
      { heading: "Gaps as governance choices", paragraphs: ["A residual gap may be accidental, transitional or deliberate. Requiring re-registration can protect local tax and traceability. Refusing a judgment for defective notice protects adjudicative legitimacy. Keeping company-name indexes separate reflects autonomous incorporation powers. The critical task is to identify whose risk the gap allocates and whether the cost is proportionate.", "Political language about a British family can obscure these allocations. The Crown Dependencies are not part of the UK. Treating them as if Westminster rules automatically applied disrespects constitutional autonomy and can produce the wrong legal result. Precision is therefore both doctrinal and constitutional ethics."] },
      { heading: "Model answer: a Manx default judgment", paragraphs: ["Assume a Manx creditor obtains a final money judgment against an English company. The creditor proves the judgment falls within the Manx reciprocal statute and the relevant UK implementing route, applies for registration in the receiving court, and supplies the prescribed evidence. The debtor may invoke jurisdictional, notice, fraud, satisfaction or public-policy safeguards provided by that regime. The English court does not enforce merely because Manx service was valid; it enforces because English recognition law gives the judgment effect after those tests.", "Change the destination to Ireland and the route must be rebuilt. Hague 2019 cannot be assumed to apply to a Manx judgment absent territorial extension. The creditor must identify an Irish statutory, treaty or common-law route. That difference is the residual gap the comparative method is designed to reveal."] },
    ],
    chain: [
      { label: "Characterise", finding: "What legal object is crossing the border?" },
      { label: "Validate", finding: "What exactly does the origin law make valid?" },
      { label: "Connect", finding: "Which forum rule chooses or recognises foreign law or status?" },
      { label: "Bridge", finding: "Treaty, reciprocal statute, common law or administrative exception?" },
      { label: "Filter", finding: "Territorial scope, commencement, exclusions, notice and public policy." },
      { label: "Effect", finding: "Enforcement, limited recognition, re-registration, evidence only or none." },
    ],
    conclusion: "Formal validity is the beginning of cross-border analysis, not its conclusion. The legally responsible answer names the receiving rule that supplies effect, states the limits of that effect and leaves an explicit gap where no bridge has been established.",
    sourceIds: ["iom-rec-act", "iom-rec-order", "jersey-rec", "hague2019", "uk-hague", "ie-hague", "ew-part74", "crown-status", "uk-import", "uk-ca"],
    furtherQuestions: ["Which Hague 2019 declarations or exclusions most affect UK–Irish commercial disputes?", "Should the UK seek extension of Hague 2019 to requesting Crown Dependencies?", "How do insolvency judgments move where Hague 2019 excludes insolvency?", "When should digital registry interoperability replace legal recognition—and when should it not?"],
  },
];

export const doctoralJurisdictionMatrix = [
  { system: "England & Wales", constitutional: "UK legal jurisdiction", service: "CPR Part 6", company: "Companies Act 2006", vehicles: "DVLA / GB regime", recognition: "CPR Part 74; Hague 2005/2019; statutes and common law" },
  { system: "Isle of Man", constitutional: "Crown Dependency; not part of UK", service: "Rules of the High Court 2009", company: "Manx Companies Acts", vehicles: "MAN / MN / MANX registry", recognition: "1968 Act and designating orders; Manx common law" },
  { system: "Ireland", constitutional: "Independent EU Member State", service: "Rules of the Superior Courts", company: "Companies Act 2014 / CRO", vehicles: "Irish registration regime", recognition: "EU instruments; Hague 2005/2019; Irish law" },
  { system: "Jersey", constitutional: "Crown Dependency; not part of UK", service: "Royal Court rules and Jersey statutes", company: "Companies (Jersey) Law 1991", vehicles: "Jersey J-mark registry", recognition: "Judgments (Reciprocal Enforcement) Law 1960" },
];

export function getDoctoralDossier(slug: string) {
  return doctoralDossiers.find((dossier) => dossier.slug === slug);
}

export function getDoctoralSources(ids: string[]) {
  return ids.map((id) => doctoralSources.find((source) => source.id === id)).filter((source): source is DoctoralSource => Boolean(source));
}
