import { buildQuestionBank, type ResearchQuestion } from "./question-data";

export type JurisdictionProfile = {
  name: string;
  group: "United Kingdom" | "Crown Dependency" | "Overseas Territory";
  legalSystem: string;
  leadAuthority: string;
  regulator: string;
  taxPosition: string;
  companyPosition: string;
  limitedPrivateMarket?: boolean;
  sources: { label: string; href: string }[];
};

const overseasFramework = { label: "UK guidance on the 14 Overseas Territories", href: "https://www.gov.uk/government/publications/guide-to-making-legislation/guide-to-making-legislation-html--2#overseas-territories" };
const crownFramework = { label: "Ministry of Justice Crown Dependencies factsheet", href: "https://www.gov.uk/government/publications/crown-dependencies-jersey-guernsey-and-the-isle-of-man" };

export const jurisdictionProfiles: JurisdictionProfile[] = [
  { name: "United Kingdom", group: "United Kingdom", legalSystem: "Three principal legal jurisdictions: England and Wales, Scotland, and Northern Ireland", leadAuthority: "The relevant UK department, HMRC, Companies House or devolved authority", regulator: "The sector regulator identified by UK legislation, commonly the FCA or PRA for financial services", taxPosition: "UK taxes apply under Acts of Parliament and devolved tax legislation where relevant", companyPosition: "Companies are principally formed under the Companies Act 2006", sources: [{ label: "UK legislation", href: "https://www.legislation.gov.uk/" }, { label: "GOV.UK", href: "https://www.gov.uk/" }] },
  { name: "Jersey", group: "Crown Dependency", legalSystem: "A distinct mixed legal system with Norman customary-law roots", leadAuthority: "Government of Jersey, Revenue Jersey and the Jersey Financial Services Commission", regulator: "Jersey Financial Services Commission", taxPosition: "A separate fiscal jurisdiction; UK tax legislation does not apply merely because Jersey is connected to the Crown", companyPosition: "Companies and other vehicles arise under Jersey legislation", sources: [{ label: "Jersey Law", href: "https://www.jerseylaw.je/" }, { label: "JFSC", href: "https://www.jerseyfsc.org/" }, crownFramework] },
  { name: "Guernsey", group: "Crown Dependency", legalSystem: "A distinct customary-law jurisdiction within the Bailiwick of Guernsey", leadAuthority: "States of Guernsey, Revenue Service and the Guernsey Financial Services Commission", regulator: "Guernsey Financial Services Commission", taxPosition: "A separate fiscal jurisdiction with locally enacted taxes", companyPosition: "Companies and fiduciary structures are governed by Bailiwick legislation", sources: [{ label: "Guernsey Legal Resources", href: "https://www.guernseylegalresources.gg/" }, { label: "GFSC", href: "https://www.gfsc.gg/" }, crownFramework] },
  { name: "Isle of Man", group: "Crown Dependency", legalSystem: "Manx law, influenced by English common law but legislated and administered separately", leadAuthority: "Isle of Man Government, Treasury and Financial Services Authority", regulator: "Isle of Man Financial Services Authority", taxPosition: "A separate fiscal jurisdiction with its own income, corporate and consumption-tax rules", companyPosition: "Manx companies may be formed under distinct 1931 or 2006 statutory regimes", sources: [{ label: "Isle of Man legislation", href: "https://legislation.gov.im/" }, { label: "Isle of Man FSA", href: "https://www.iomfsa.im/" }, crownFramework] },
  { name: "Anguilla", group: "Overseas Territory", legalSystem: "Eastern Caribbean common-law system under Anguillan legislation and constitution", leadAuthority: "Government of Anguilla and the relevant local ministry or registry", regulator: "Anguilla Financial Services Commission", taxPosition: "Local taxes and duties apply; UK tax rules are not automatically local law", companyPosition: "Entities exist under Anguillan company and financial-services legislation", sources: [{ label: "Government of Anguilla", href: "https://gov.ai/" }, { label: "Anguilla FSC", href: "https://www.fsc.org.ai/" }, overseasFramework] },
  { name: "Bermuda", group: "Overseas Territory", legalSystem: "Bermudian common law and local statutes under a written constitution", leadAuthority: "Government of Bermuda and the Office of the Tax Commissioner", regulator: "Bermuda Monetary Authority", taxPosition: "Local taxes and the corporate income tax framework apply according to Bermudian legislation", companyPosition: "Companies, partnerships and insurance structures are creatures of Bermudian law", sources: [{ label: "Bermuda Laws Online", href: "https://www.bermudalaws.bm/" }, { label: "Bermuda Monetary Authority", href: "https://www.bma.bm/" }, overseasFramework] },
  { name: "British Antarctic Territory", group: "Overseas Territory", legalSystem: "A specialist territorial regime administered by a Commissioner, subject to the Antarctic Treaty System", leadAuthority: "Commissioner for the British Antarctic Territory", regulator: "No general domestic financial-services market regulator", taxPosition: "No ordinary resident private tax economy", companyPosition: "No ordinary local company-formation market", limitedPrivateMarket: true, sources: [{ label: "British Antarctic Territory government", href: "https://www.britishantarcticterritory.org.uk/" }, overseasFramework] },
  { name: "British Indian Ocean Territory", group: "Overseas Territory", legalSystem: "A specialist territorial regime administered by a Commissioner", leadAuthority: "British Indian Ocean Territory Administration", regulator: "No ordinary domestic financial-services market regulator", taxPosition: "No permanent civilian tax base", companyPosition: "No ordinary local company-formation market", limitedPrivateMarket: true, sources: [{ label: "BIOT Administration", href: "https://www.biot.gov.io/" }, overseasFramework] },
  { name: "British Virgin Islands", group: "Overseas Territory", legalSystem: "Virgin Islands common law and local statutes, with the Eastern Caribbean Supreme Court", leadAuthority: "Government of the Virgin Islands, Inland Revenue and Registry of Corporate Affairs", regulator: "BVI Financial Services Commission", taxPosition: "A separate local tax system; substance, reporting and international standards can still apply", companyPosition: "Business companies and limited partnerships are governed by Virgin Islands legislation", sources: [{ label: "BVI Laws", href: "https://bvi.gov.vg/laws" }, { label: "BVI FSC", href: "https://www.bvifsc.vg/" }, overseasFramework] },
  { name: "Cayman Islands", group: "Overseas Territory", legalSystem: "Cayman Islands common law and local statutes, with final appeal generally to the Privy Council", leadAuthority: "Cayman Islands Government, Department for International Tax Cooperation and General Registry", regulator: "Cayman Islands Monetary Authority", taxPosition: "No general income or corporate profits tax, but fees, duties, substance and reporting regimes may apply", companyPosition: "Companies, partnerships, trusts and foundation companies arise under Cayman legislation", sources: [{ label: "Cayman legislation", href: "https://legislation.gov.ky/" }, { label: "CIMA", href: "https://www.cima.ky/" }, overseasFramework] },
  { name: "Falkland Islands", group: "Overseas Territory", legalSystem: "Falkland Islands law, including locally enacted and applied English law", leadAuthority: "Falkland Islands Government and the relevant statutory office", regulator: "Local public authorities; no large offshore financial-services market", taxPosition: "Local income and corporation taxes apply under Falkland Islands legislation", companyPosition: "Local company law applies in a small domestic economy", sources: [{ label: "Falkland Islands legislation", href: "https://www.legislation.gov.fk/" }, { label: "Falkland Islands Government", href: "https://www.falklands.gov.fk/" }, overseasFramework] },
  { name: "Gibraltar", group: "Overseas Territory", legalSystem: "Gibraltar common law and statutes, strongly influenced by UK and retained EU-derived law", leadAuthority: "Government of Gibraltar, Income Tax Office and Companies House Gibraltar", regulator: "Gibraltar Financial Services Commission", taxPosition: "A separate territorial tax system applies under Gibraltar legislation", companyPosition: "Companies and regulated structures are governed by Gibraltar law", sources: [{ label: "Gibraltar Laws", href: "https://www.gibraltarlaws.gov.gi/" }, { label: "Gibraltar FSC", href: "https://www.fsc.gi/" }, overseasFramework] },
  { name: "Montserrat", group: "Overseas Territory", legalSystem: "Montserrat common law and local statutes within the Eastern Caribbean court system", leadAuthority: "Government of Montserrat and the relevant local ministry or registry", regulator: "Eastern Caribbean Central Bank for banking, with local authorities for other fields", taxPosition: "Local income, company and customs rules apply", companyPosition: "Local company legislation applies in a small economy", sources: [{ label: "Government of Montserrat", href: "https://www.gov.ms/" }, { label: "Montserrat legislation", href: "https://agc.gov.ms/" }, overseasFramework] },
  { name: "Pitcairn Islands", group: "Overseas Territory", legalSystem: "Pitcairn ordinances and applied English law under the territory's constitution", leadAuthority: "Governor of Pitcairn and Island Council", regulator: "No ordinary financial-services market regulator", taxPosition: "No conventional large-scale private tax market", companyPosition: "No ordinary offshore company-formation market", limitedPrivateMarket: true, sources: [{ label: "Pitcairn government", href: "https://www.government.pn/" }, overseasFramework] },
  { name: "Saint Helena, Ascension and Tristan da Cunha", group: "Overseas Territory", legalSystem: "A single territory with distinct island legal administrations and locally applicable ordinances", leadAuthority: "The Governor and the relevant island government or Administrator", regulator: "Local public authorities; sector regulation depends on the island and activity", taxPosition: "Local taxation differs across the three island jurisdictions", companyPosition: "Local ordinances govern entities; this is not a single mass-market offshore regime", sources: [{ label: "Saint Helena government", href: "https://www.sainthelena.gov.sh/" }, { label: "Territory laws", href: "https://www.sainthelena.gov.sh/government/legislation/" }, overseasFramework] },
  { name: "South Georgia and the South Sandwich Islands", group: "Overseas Territory", legalSystem: "A specialist environmental and administrative regime under a Commissioner", leadAuthority: "Commissioner for South Georgia and the South Sandwich Islands", regulator: "Government administration and licensing authorities", taxPosition: "No permanent civilian tax base", companyPosition: "No ordinary local company-formation market", limitedPrivateMarket: true, sources: [{ label: "Government of SGSSI", href: "https://gov.gs/" }, overseasFramework] },
  { name: "Sovereign Base Areas of Akrotiri and Dhekelia", group: "Overseas Territory", legalSystem: "Sovereign Base Areas law administered by the SBA Administration, with close alignment to the Republic of Cyprus where appropriate", leadAuthority: "Sovereign Base Areas Administration", regulator: "SBA Administration and relevant Republic of Cyprus arrangements", taxPosition: "The bases are not promoted as a commercial or fiscal jurisdiction", companyPosition: "No ordinary offshore company-formation market", limitedPrivateMarket: true, sources: [{ label: "SBA Administration", href: "https://www.sbaadministration.org/" }, overseasFramework] },
  { name: "Turks and Caicos Islands", group: "Overseas Territory", legalSystem: "Turks and Caicos Islands common law and local statutes under a written constitution", leadAuthority: "TCI Government, Revenue Department and Companies Registry", regulator: "Turks and Caicos Islands Financial Services Commission", taxPosition: "No general personal or corporate income tax, but duties, fees and reporting obligations apply", companyPosition: "Companies and regulated structures are governed by TCI legislation", sources: [{ label: "TCI legislation", href: "https://www.gov.tc/agc/laws" }, { label: "TCI FSC", href: "https://tcifsc.tc/" }, overseasFramework] },
];

export const territoryNames = jurisdictionProfiles.map((profile) => profile.name);

const domainBaseline: Record<string, (profile: JurisdictionProfile) => string> = {
  "corporate-structuring": (p) => `${p.companyPosition}. The constitutionally separate status of ${p.name} means a UK or foreign entity label cannot be imported without checking local formation, control and substance rules.`,
  "tax-capital": (p) => `${p.taxPosition}. Residence, source, character and relief must be established from local legislation and any applicable UK arrangement or international instrument.`,
  "trusts-estates": (p) => `Trust, succession and creditor questions are determined by ${p.legalSystem.toLowerCase()}, including local conflicts rules; an English trust-law result is not automatic.`,
  "residency-mobility": (p) => `Immigration status, tax residence, domicile and any local belonger or permanent-status concept are separate tests administered by ${p.leadAuthority}.`,
  "maritime-aviation": (p) => `Registration and operating rights depend on the local registry, enabling legislation and international instruments extended to ${p.name}; flag status alone does not settle tax or liability.`,
  "finance-crypto": (p) => `${p.regulator} is the starting point for the regulatory perimeter. A token, protocol or payment model must be mapped to local licensing, AML, custody and promotion rules.`,
  "litigation-insolvency": (p) => `Jurisdiction, recognition and creditor remedies arise under ${p.legalSystem.toLowerCase()}. Local procedure and any reciprocal or model-law provisions must be identified before assuming recognition.`,
  "intellectual-property": (p) => `IP protection depends on local legislation, any extension of UK rights and applicable international instruments; UK registration is not universally self-executing in ${p.name}.`,
  "employment-services": (p) => `Worker status, payroll, immigration permission and professional licensing are separate local questions overseen by ${p.leadAuthority}.`,
  "trade-sanctions": (p) => `Customs, origin, export-control and sanctions treatment depends on local law plus UK measures or treaties validly extended or implemented in ${p.name}.`,
};

const lensFinding: Record<string, string> = {
  "legal-basis": "The mechanism is available only to the extent that current local primary or secondary legislation creates, recognises or permits it; administrative practice cannot replace a missing power.",
  eligibility: "Eligibility turns on the defined person, asset, transaction, licence category and territorial nexus. Exclusions and anti-avoidance definitions must be read before relying on the headline rule.",
  classification: "Classification is functional, not label-driven. Tax, regulatory and private-law classifications may diverge, and a foreign classification does not bind the local authority.",
  substance: "The evidence should show real decision-making, people, expenditure, records and commercial purpose proportionate to the activity; paper control alone is insufficient where substance rules apply.",
  disclosure: "Check formation and licensing filings, beneficial-ownership records, tax returns, automatic-exchange reporting, suspicious-activity duties and transaction-specific notifications.",
  "anti-abuse": "The arrangement remains exposed to specific anti-avoidance provisions, sham or substance doctrines, transfer-pricing rules and foreign anti-abuse rules where another jurisdiction has nexus.",
  enforcement: "The competent authority can use information requests, inspection, licence conditions, assessments, civil penalties, director remedies and—where legislation provides—criminal enforcement.",
  precedent: "Only reported local decisions, binding appellate decisions and formally applicable persuasive authorities should be treated as precedent; factual distinctions and the date of the statute matter.",
  "cross-border": "Resolve residence, source, governing law, forum, treaty coverage, recognition and information-exchange separately. The territorial connection does not remove another jurisdiction's taxing or regulatory claim.",
  reform: "Confirm the commencement date and transitional rules of every reform. Policy announcements and bills are not operative law, while preserved legitimate activity may be subject to new reporting or substance safeguards.",
};

export type AnsweredQuestion = ResearchQuestion & {
  answer: { status: string; summary: string; evidence: string[]; authorities: { label: string; href: string }[]; reviewedAt: string };
};

export function buildAnsweredQuestionBank(jurisdiction: string): AnsweredQuestion[] {
  const profile = jurisdictionProfiles.find((item) => item.name === jurisdiction) ?? jurisdictionProfiles[0];
  return buildQuestionBank(profile.name).map((question) => {
    const limited = profile.limitedPrivateMarket && ["corporate-structuring", "tax-capital", "trusts-estates", "finance-crypto", "intellectual-property"].includes(question.domainSlug);
    const status = limited ? "Not ordinarily applicable" : "Templated baseline";
    const opening = limited
      ? `${profile.name} has no ordinary private market for this mechanism. A proposed use would first require proof of an express legal basis and approval from ${profile.leadAuthority}; it should not be treated as an available offshore route.`
      : domainBaseline[question.domainSlug](profile);
    return { ...question, answer: {
      status,
      summary: `${opening} ${lensFinding[question.lensSlug]} This is the defensible baseline answer for ${question.topic}; a transaction-specific conclusion requires the current text, commencement provisions and facts.`,
      evidence: [
        `Current local legislation and commencement history for ${question.topic}`,
        `Written position, register entry or licence record from ${profile.leadAuthority}`,
        question.lensSlug === "precedent" ? "Full judgment and subsequent appellate treatment" : "Contemporaneous ownership, control, purpose and transaction records",
      ],
      authorities: profile.sources,
      reviewedAt: "2026-08-16",
    } };
  });
}
