import Link from "next/link";
import { contextReviewedAt, contextTerritories } from "./data";

export default function ContextDirectoryPage() {
  const schema = { "@context": "https://schema.org", "@type": "Dataset", name: "1,400 structural legal context answers across the British Overseas Territories", dateModified: contextReviewedAt, spatialCoverage: contextTerritories.map((territory) => territory.name), variableMeasured: ["service", "corporate identity", "registration", "domicile", "recognition", "formal validity", "limitation", "disclosure"], isAccessibleForFree: true };
  return <main className="context-shell">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <header className="kb-header"><Link className="brand" href="/"><span className="brand-mark">BA</span><span><b>BRITANNIC ATLAS</b><small>STRUCTURAL CONTEXT LIBRARY</small></span></Link><div className="kb-header-links"><Link className="kb-back" href="/doctoral">Doctoral module</Link><Link className="kb-back" href="/territories">Territories</Link><Link className="kb-back" href="/">← Atlas</Link></div></header>
    <section className="context-index-hero"><div><span>14 TERRITORIES × 100 ANSWERS · REVIEWED {contextReviewedAt}</span><h1>The law between<br /><em>the systems.</em></h1></div><div><p>A territory-by-territory answer bank about service, identity, registration, domicile, recognition, formal validity, time and disclosure.</p><a href="#territories">CHOOSE A TERRITORY <b>↓</b></a></div></section>
    <section className="context-index-signal"><div><strong>1,400</strong><span>new contextual answers</span></div><div><strong>14</strong><span>separate legal systems</span></div><div><strong>100</strong><span>questions per territory</span></div><p><b>Reading rule</b> Each answer separates a defensible structural baseline from the local source that must be checked. Exceptional territories receive an explicit limited-application finding rather than an invented private market.</p></section>
    <section className="context-index-intro"><span>01 / THE COMPARATIVE LENS</span><h2>Validity at home.<br />Effect abroad.</h2><p>The answers identify where local law stops, which receiving rule could bridge the gap, and what evidence a researcher would need before reaching a case-specific conclusion.</p></section>
    <section className="context-territory-grid" id="territories">{contextTerritories.map((territory, index) => <Link href={`/territories/${territory.slug}/context`} key={territory.slug}><span>{String(index + 1).padStart(2, "0")} · {territory.code}</span><div><b>{territory.name}</b><small>{territory.region}</small></div><p>{territory.exceptional ? "Exceptional context · no ordinary large private market" : "100 locally framed structural answers"}</p><i>OPEN LIBRARY ↗</i></Link>)}</section>
    <section className="context-method"><div><span>02 / ANSWER ARCHITECTURE</span><h2>Rule → limit →<br />bridge → gap.</h2></div><ol><li><b>01</b><span>State the local baseline</span></li><li><b>02</b><span>Identify the territorial limit</span></li><li><b>03</b><span>Find an express recognition bridge</span></li><li><b>04</b><span>Record what still needs fresh compliance</span></li></ol></section>
  </main>;
}
