import test from 'node:test';import assert from 'node:assert/strict';
import {answer} from '../lib/brain.mjs';import {KnowledgeBase} from '../lib/kb.mjs';
test('answer generation reports its stage before waiting for a model response',async t=>{
 const kb=new KnowledgeBase(':memory:');t.after(()=>kb.close());let release,entered;const waiting=new Promise(r=>{release=r;}),started=new Promise(r=>{entered=r;}),events=[];
 const work=answer({kb,question:'Explain the Manx flag symbolism',sessionId:'progress-test',emit:(event,data)=>events.push({event,data}),runModel:async options=>{entered();await waiting;options.onDelta('Synthetic answer.');return {costUsd:0};}});
 await started;try{assert.ok(events.some(e=>e.event==='progress'&&e.data.phase==='thinking'),'The model is running but no thinking-stage event reached the client');}finally{release();await work;}
});

import {createActivityStore,createProgressSpeechGate,toolActivity} from '../public/activity-progress.mjs';
test('heartbeats keep the connection current without inventing progress',()=>{let now=0;const s=createActivityStore({clock:()=>now});s.start('a','searching');now=16000;s.update('a',{heartbeat:true});const t=s.snapshot()[0];assert.equal(t.waiting,true);assert.equal(t.disconnected,false);assert.equal(t.phase,'searching');assert.equal(t.changed,0);assert.match(t.note,/Still waiting/);now=37000;assert.equal(s.snapshot()[0].disconnected,true);assert.doesNotMatch(s.snapshot()[0].title,/Searching/);});
test('a finished or cancelled task cannot be revived by late events',()=>{let now=0;const s=createActivityStore({clock:()=>now});s.start('a');s.finish('a','stopped');s.update('a',{phase:'writing'});assert.equal(s.snapshot()[0].title,'Stopped');now=9000;assert.equal(s.snapshot().length,0);s.update('a',{phase:'thinking'});assert.equal(s.snapshot().length,0);});
test('independent answer and review activities do not overwrite each other',()=>{const s=createActivityStore();s.start('answer:a','searching');s.start('review:b','reviewing');s.finish('answer:a');assert.equal(s.snapshot().find(t=>t.id==='review:b').terminal,null);s.clear();s.update('review:b',{phase:'synthesising'});assert.equal(s.snapshot().length,0);});
test('tool status is projected without source content, URLs or secrets',()=>{assert.deepEqual(toolActivity({name:'search_web',status:'working',message:'SECRET',url:'https://example.test/?token=SECRET'}),{phase:'searching'});assert.equal(toolActivity({name:'execute_private_command',status:'working'}),null);assert.match(toolActivity({name:'read_page',status:'unavailable'}).detail,/unavailable/);});
test('spoken progress is throttled, optional and suppressed during speech or microphone use',()=>{let now=0;const gate=createProgressSpeechGate({clock:()=>now}),s=createActivityStore({clock:()=>now});s.start('a','searching');assert.equal(gate.next(s.snapshot()),null);now=3000;assert.match(gate.next(s.snapshot()),/Searching/);now=4000;s.update('a',{phase:'reading'});assert.equal(gate.next(s.snapshot()),null);now=19000;assert.equal(gate.next(s.snapshot(),{busy:true}),null);assert.equal(gate.next(s.snapshot(),{listening:true}),null);assert.equal(gate.next(s.snapshot(),{hidden:true}),null);assert.equal(gate.next(s.snapshot(),{enabled:false}),null);assert.match(gate.next(s.snapshot()),/Reading/);s.finish('a');now=50000;assert.equal(gate.next(s.snapshot()),null);});
test('elapsed time freezes on completion and status history remains bounded',()=>{let now=0;const s=createActivityStore({clock:()=>now});s.start('a');for(let i=0;i<20;i++){now+=1000;s.update('a',{phase:i%2?'reading':'searching'});}s.finish('a');now+=5000;assert.equal(s.snapshot()[0].elapsed,'20s');assert.equal(s.snapshot()[0].history.length,4);});

test('MOMM: nine live activities remain visible and the oldest can report failure',()=>{const s=createActivityStore();for(let i=0;i<9;i++)s.start('review:'+i,'reviewing');assert.equal(s.snapshot().length,9);s.finish('review:0','failed');assert.equal(s.snapshot().find(t=>t.id==='review:0').title,'Could not finish');});
test('a new request removes terminal clutter while retaining independent work',()=>{const s=createActivityStore();s.start('a');s.finish('a');s.start('review:b','reviewing');s.start('c');assert.deepEqual(s.snapshot().map(t=>t.id),['review:b','c']);});
test('a fresh observation may resume explicitly, but a late phase cannot revive a paused one',()=>{const s=createActivityStore();s.start('review:a');s.finish('review:a','paused');s.update('review:a',{phase:'reviewing'});assert.equal(s.snapshot()[0].terminal,'paused');s.clear();s.start('review:a','reviewing');assert.equal(s.snapshot()[0].terminal,null);});
test('a buffered heartbeat clears a connection warning without pretending work advanced',()=>{let now=0;const s=createActivityStore({clock:()=>now});s.start('a','thinking');now=60000;assert.equal(s.snapshot()[0].disconnected,true);s.update('a',{heartbeat:true});assert.equal(s.snapshot()[0].disconnected,false);assert.equal(s.snapshot()[0].waiting,true);assert.equal(s.snapshot()[0].phase,'thinking');});
test('system clock adjustment cannot inflate the elapsed duration',()=>{const old=Date.now;try{const s=createActivityStore();s.start('a');Date.now=()=>old()+3600000;assert.equal(s.snapshot()[0].elapsed,'0s');}finally{Date.now=old;}});

import vm from 'node:vm';import {readFileSync} from 'node:fs';
test('voice-first default enables progress unless explicitly muted',()=>{const source=readFileSync(new URL('../public/app.js',import.meta.url),'utf8'),input={checked:true};const c=vm.createContext({$:()=>input,localStorage:{getItem:()=>null}});vm.runInContext(source.slice(source.indexOf('  const spokenProgress='),source.indexOf('  const activity=mountActivityProgress')),c);assert.equal(input.checked,true);});

import {sseStart} from '../lib/bus.mjs';import {EventEmitter} from 'node:events';
test('server heartbeats arrive every five seconds and stop when the response closes',t=>{t.mock.timers.enable({apis:['setInterval']});const res=new EventEmitter(),writes=[];res.writeHead=()=>{};res.write=s=>writes.push(s);sseStart(res);t.mock.timers.tick(4999);assert.equal(writes.length,1);t.mock.timers.tick(1);assert.match(writes[1],/^event: heartbeat/);assert.doesNotMatch(writes[1],/tool|claim|progress/);res.emit('close');t.mock.timers.tick(10000);assert.equal(writes.length,2);});
test('first answer speech preempts progress without cancelling the active request',()=>{const source=readFileSync(new URL('../public/app.js',import.meta.url),'utf8'),events=[],controller={};const c=vm.createContext({isCurrentResponse:()=>true,activeProgress:true,hush:o=>{assert.equal(o.cancelAnswer,false);assert.equal(o.preserveListening,true);assert.equal(o.clearDeferred,false);events.push('silence');},say:t=>events.push(t)});vm.runInContext(source.slice(source.indexOf('  function handle('),source.indexOf('  async function vote(')),c);c.handle('sentence',{text:'The answer.'},{querySelector:()=>({})},1,controller);assert.deepEqual(events,['silence','The answer.']);});

test('a raw tool message cannot overwrite the safe progress announcement',()=>{const source=readFileSync(new URL('../public/app.js',import.meta.url),'utf8'),messages=[];const c=vm.createContext({isCurrentResponse:()=>true,toolActivity,noteActivity:(_id,stage)=>messages.push(stage.phase),setLiveStatus:text=>messages.push(text),cleanText:text=>text});vm.runInContext(source.slice(source.indexOf('  function handle('),source.indexOf('  async function vote(')),c);c.handle('tool',{name:'read_page',status:'working',message:'C:/private/SECRET'},{querySelector:()=>({})},1,{activityId:'a'});assert.deepEqual(messages,['reading']);});

test('a brief audio reset cannot label an active task Ready',()=>{const source=readFileSync(new URL('../public/app.js',import.meta.url),'utf8'),messages=[];const c=vm.createContext({state:'thinking',orb:{setAttribute(){}},orbLabel:{},maniVisual:{setState(){}},$:()=>null,activity:{snapshot:()=>[{terminal:null,title:'Preparing your request',note:''}]},setLiveStatus:s=>messages.push(s)});vm.runInContext(source.slice(source.indexOf('  function setState('),source.indexOf('  // ---------- speech recognition')),c);c.setState('idle');c.setState('thinking');assert.deepEqual(messages,['Preparing your request']);});

test('progress begins after one second and tracks the latest stage within six seconds',()=>{let now=0;const s=createActivityStore({clock:()=>now}),gate=createProgressSpeechGate({clock:()=>now});s.start('a','searching');now=1000;assert.match(gate.next(s.snapshot()),/Searching/);now=2000;s.update('a',{phase:'reading'});assert.equal(gate.next(s.snapshot()),null);now=7000;s.update('a',{phase:'checking'});const next=gate.next(s.snapshot());assert.match(next,/Checking/);assert.doesNotMatch(next,/Reading/);});
test('progress speech rotates between simultaneous review and search work',()=>{let now=0;const s=createActivityStore({clock:()=>now}),gate=createProgressSpeechGate({clock:()=>now});s.start('search','searching');s.start('review','reviewing');now=1000;assert.match(gate.next(s.snapshot()),/MOMM/);now=7000;assert.match(gate.next(s.snapshot()),/Searching/);});
test('explicitly muted progress remains muted across reload and inaccessible storage keeps voice on',()=>{const source=readFileSync(new URL('../public/app.js',import.meta.url),'utf8'),snippet=source.slice(source.indexOf('  const spokenProgress='),source.indexOf('  const activity=mountActivityProgress'));for(const saved of ['off','on',null,'invalid','throw']){const input={checked:true},c=vm.createContext({$:()=>input,localStorage:{getItem:()=>{if(saved==='throw')throw Error('denied');return saved;}}});vm.runInContext(snippet,c);assert.equal(input.checked,saved!=='off');}});
