import test from 'node:test';import assert from 'node:assert/strict';import {KnowledgeBase} from '../lib/kb.mjs';import {ConversationStore} from '../lib/conversations.mjs';import {ResultStore} from '../lib/results.mjs';import {answer} from '../lib/brain.mjs';import {runLiveTools} from '../lib/live-tools.mjs';
test('fresh reads still retrieve stored knowledge and do not repeat exact live/indexed excerpts',async t=>{const kb=new KnowledgeBase(':memory:');t.after(()=>kb.close());let fetched,lookups=0;const live=await runLiveTools({question:'Read https://www.tynwald.org.im/history',allowRecovery:false,get:async url=>({url,headers:{'content-type':'text/html'},body:'<main><h1>Manx constitutional history</h1><p>Synthetic Manx constitutional history includes the independent institutions described here.</p></main>'})});
 const stored={...live.claims[0],id:'c_duplicate'};
 await answer({kb,question:'Find sources for Manx constitutional history',sessionId:'s',liveTools:async()=>live,retrieval:{syncLedger:async()=>{},stats:()=>({}),focus:async()=>{lookups++;return {claims:[stored,{id:'c_other',text:'A separate synthetic institutional history finding.',topic:'Manx constitutional history',status:'single_source',trust:.55,sources:[{url:'https://www.gov.im/history'}]}],retrievalMode:'hybrid',coverage:'partial',budgetUsed:1};}},emit:(e,d)=>{if(e==='focus')fetched=d;},runModel:async o=>{o.onDelta('This evidence leaves some questions unresolved.');return {costUsd:0};}});
 assert.equal(lookups,1);assert.equal(fetched.claims.length,2);assert.ok(fetched.claims.some(c=>c.id==='c_other'));assert.ok(!fetched.claims.some(c=>c.id==='c_duplicate'));
});
test('saved review corrections reach subsequent context as unverified critique without leaking sessions or placeholders',t=>{const kb=new KnowledgeBase(':memory:');t.after(()=>kb.close());const c=new ConversationStore(kb.db),r=new ResultStore(kb.db);c.ensure('s');c.ensure('other');r.put('s','episode:one','old',{ok:true,answer:'SYNTHETIC_CORRECTION: verify the date against the primary record.',operation:{phase:'completed'},review:{runId:'r'}});r.put('other','episode:two','old',{ok:true,answer:'OTHER_SESSION_SECRET',operation:{phase:'completed'}});r.put('s','episode:bad','old',{ok:true,answer:'Test answer to isolate schema parsing issue.',operation:{phase:'completed'}});const memory=c.context('s','What was corrected?').text;assert.match(memory,/SYNTHETIC_CORRECTION/);assert.match(memory,/unverified critique/i);assert.doesNotMatch(memory,/OTHER_SESSION_SECRET|Test answer to isolate/);assert.match(memory,/unusable_review_answer/);});

test('a saved excerpt is indexed and retrieved, while tampered or expired records are excluded',async t=>{const {VectorStore}=await import('../lib/vector-store.mjs');const {ManxRetrieval}=await import('../lib/manx-retrieval.mjs');const {persistPublicEvidence,syncPublicEvidence}=await import('../lib/evidence-ledger.mjs');const kb=new KnowledgeBase(':memory:'),store=new VectorStore(':memory:',{modelId:'fixture',dimensions:3}),retrieval=new ManxRetrieval(kb,null,{store,getEmbedder:async()=>({countTokens:text=>text.split(/\s+/).length,embed:async texts=>texts.map(()=>[1,0,0])})});t.after(()=>{retrieval.close();kb.close();});const url='https://www.tynwald.org.im/history',live=await runLiveTools({question:'Read '+url,allowRecovery:false,get:async()=>({url,headers:{'content-type':'text/html'},body:'<main><p>Synthetic Manx constitutional history describes the island legislature and institutions.</p></main>'})});const receipt=persistPublicEvidence(kb,live,{question:'Read '+url});await syncPublicEvidence(receipt,retrieval);assert.equal(receipt.index.missing,0);assert.equal((await retrieval.focus('Manx constitutional history')).retrievalMode,'hybrid');assert.ok((await retrieval.focus('Manx constitutional history')).claims.some(c=>c.id===receipt.ids[0]));kb.db.prepare('UPDATE claims SET text=? WHERE id=?').run('Tampered Manx constitutional history.',receipt.ids[0]);assert.ok(!(await retrieval.focus('Manx constitutional history')).claims.some(c=>c.id===receipt.ids[0]));await retrieval.syncLedger('manual');assert.equal(retrieval.stats().ledger.indexable,0);assert.equal(retrieval.stats().ledger.stale,0);});
test('a nonthrowing index failure reports partial learning and can be reconciled later',async()=>{const {syncPublicEvidence}=await import('../lib/evidence-ledger.mjs');const receipt={stored:1};await syncPublicEvidence(receipt,{syncLedger:async()=>({state:'failed'}),stats:()=>({ledger:{indexable:1,indexed:0,missing:1,stale:0}})});assert.equal(receipt.learningStatus,'saved_not_fully_indexed');await syncPublicEvidence(receipt,{syncLedger:async()=>({state:'current'}),stats:()=>({ledger:{indexable:1,indexed:1,missing:0,stale:0}})});assert.equal(receipt.learningStatus,'saved_and_indexed');});

test('a long saved source returns its relevant indexed passage instead of being dropped from the answer budget',async t=>{const {VectorStore}=await import('../lib/vector-store.mjs');const {ManxRetrieval}=await import('../lib/manx-retrieval.mjs');const {persistPublicEvidence,syncPublicEvidence}=await import('../lib/evidence-ledger.mjs');const kb=new KnowledgeBase(':memory:'),store=new VectorStore(':memory:',{modelId:'fixture',dimensions:3}),r=new ManxRetrieval(kb,null,{store,getEmbedder:async()=>({countTokens:text=>text.split(/\s+/).length,embed:async texts=>texts.map(()=>[1,0,0])})});t.after(()=>{r.close();kb.close();});const url='https://www.tynwald.org.im/history',body='<main><p>Synthetic Manx Revestment customs history identifies the Atholl transfer.</p>'+Array.from({length:35},(_,i)=>'<p>Public institutional background section '+i+' '+('General institutional background and explanatory material. '.repeat(7))+'</p>').join('')+'</main>';const live=await runLiveTools({question:'Read '+url,allowRecovery:false,get:async()=>({url,headers:{'content-type':'text/html'},body})});const receipt=persistPublicEvidence(kb,live,{question:'Read '+url});await syncPublicEvidence(receipt,r);const original=kb.getClaim(receipt.ids[0]);assert.ok(original.text.length>9000);const focus=await r.focus('Revestment customs Atholl transfer'),c=focus.claims.find(c=>c.id===original.id);assert.ok(c,'The indexed source must fit by its matching passage');assert.ok(c.text.length<original.text.length);assert.match(c.text,/Atholl transfer/);assert.equal(kb.getClaim(original.id).text,original.text);assert.equal(r.stats().integrity.ok,true);});
