import test from 'node:test';import assert from 'node:assert/strict';
import {createDialogueState,resolveDialogue} from '../lib/dialogue.mjs';import {liveRequest} from '../lib/live-tools.mjs';import {usableReviewAnswer} from '../lib/review-quality.mjs';import {KnowledgeBase} from '../lib/kb.mjs';import {ResultStore} from '../lib/results.mjs';
const subject='Find the Atholl family history and the current-money equivalents of the 1765 and 1828 Isle of Man purchase payments';
const state=()=>({...createDialogueState(),lastSubstantiveQuestion:subject,lastAnswerSubject:subject,lastSubstantiveTurn:{question:subject,semanticKey:'atholl'},lastCompletedKey:'atholl',pendingAction:{kind:'research',subject,jurisdiction:'Isle of Man',researchMode:'live_sources',status:'offered',origin:{kind:'turn',semanticKey:'atholl'}},lastOperation:{kind:'search'}});
test('natural retry and read-follow-up variants execute the bound task without another confirmation',()=>{for(const q of ['Try it.','Then go find and read it.','Go and find it.','Please try that.']){const r=resolveDialogue(q,state());assert.equal(r.route,'research',q);assert.match(r.canonical,/Atholl/i);assert.match(r.canonical,/1765/);assert.equal(r.researchMode,'live_sources');}assert.equal(resolveDialogue('Try it.',createDialogueState()).route,'clarify');});
test('find the answers and use MOMM retains both source search and review',()=>{for(const q of ['Find the answers and use MOM to help you.','Find the answers and use MOMM.','Find the evidence and run MOMM.']){const r=resolveDialogue(q,state());assert.equal(r.route,'research',q);assert.equal(r.reviewRequested,true);assert.match(r.canonical,/Atholl/i);}assert.notEqual(resolveDialogue("Don't find the answers or use MOMM.",state()).reviewRequested,true);});
test('an explicit request to find references starts discovery rather than explaining that it could search',()=>{const q='Can you find any references to anybody ever proposing Manx independence? And also research Manx freehold tenure. Dig deep.';assert.equal(liveRequest(q)?.name,'search_web');assert.equal(liveRequest('How much was it sold for? Some deeper research into the tenure type of the freehold and the Manx title registry.')?.name,'search_web');});
test('placeholder synthesis cannot pass as a reviewed answer',()=>{for(const text of ['Test answer to isolate schema parsing issue.','Dummy response for testing.','Placeholder answer.'])assert.equal(usableReviewAnswer(text),false,text);assert.equal(usableReviewAnswer('The test described in the question does not establish ownership.'),true);});
test('old placeholder review is quarantined when read without altering its stored record',t=>{const kb=new KnowledgeBase(':memory:');t.after(()=>kb.close());const store=new ResultStore(kb.db),payload={ok:true,answer:'Test answer to isolate schema parsing issue.',review:{reviewers:[{agent:'codex',status:'success'}]},operation:{id:'bad',phase:'completed'}};store.put('s','episode:old','old answer',payload);const result=store.get('s','episode:old');assert.equal(result.ok,false);assert.equal(result.reason,'unusable_review_answer');assert.equal(result.review.reviewers.length,1);assert.equal(JSON.parse(kb.db.prepare('SELECT payload FROM oracle_results').get().payload).ok,true);});

test('a summary-and-review misroute in an older conversation restores the existing factual task',async t=>{const {ConversationStore}=await import('../lib/conversations.mjs');const kb=new KnowledgeBase(':memory:');t.after(()=>kb.close());const c=new ConversationStore(kb.db);const subject='Tell me about the Atholl family and the 1765 purchase payment';c.start({id:'fact',sessionId:'restore',question:subject,resolution:{route:'answer',canonical:subject,jurisdiction:'Isle of Man'}});c.finish('fact',{answer:'The source check failed.',metadata:{meta:{nextSteps:[{kind:'research',subject,researchMode:'live_sources'}]}}});const recap='Look over this entire context chat. Put it together in an answer and then push that into MUM for review.';c.start({id:'recap',sessionId:'restore',question:recap,resolution:{route:'answer',canonical:recap,jurisdiction:'Isle of Man'}});c.finish('recap',{answer:'A summary.'});c.saveState('restore',{...createDialogueState(),lastSubstantiveQuestion:recap,lastAnswerSubject:recap,pendingAction:null});const r=resolveDialogue('Try it.',c.loadState('restore'));assert.equal(r.route,'research');assert.match(r.canonical,/Atholl/i);assert.doesNotMatch(r.canonical,/push that into/);});

test('upgrade diagnostics preserve the selected factual subject instead of becoming the next search',()=>{const r=resolveDialogue("I've upgraded you, can you try again? Are you any better than you were previously?",state());assert.equal(r.conversationMeta,true);assert.match(r.state.lastSubstantiveQuestion,/Atholl/i);assert.notEqual(r.route,'research');});
