import test from 'node:test';import assert from 'node:assert/strict';
import {deliberateEpisode,MommHourlyAllowance,EpisodeDeliberationGate} from '../lib/deliberate.mjs';
import {interactionCommand} from '../lib/interaction-policy.mjs';import {createDialogueState,resolveDialogue} from '../lib/dialogue.mjs';
import {conversationRepairQuestion} from '../public/conversation-policy.mjs';import {runLiveTools,LiveLookupBudget} from '../lib/live-tools.mjs';
const episode={id:'ep_recovery',session_id:'s',question:'What does this public chart establish?',resolved_question:'What does this public chart establish?',jurisdiction:'United Kingdom',answer:'The regional depth range does not establish a crossing profile.',status:'model_prior',confidence:.3,claims_used:[],sources:[]};
const peers={run_id:'rev_test',reviewers:[{agent:'codex',status:'success',verdict:'MODIFY',confidence:.9},{agent:'antigravity',status:'success',verdict:'ACCEPT',confidence:.8}],findings:[]};
const options=()=>({episode,dispatch:async()=>peers,minSuccess:2,allowance:new MommHourlyAllowance(),gate:new EpisodeDeliberationGate()});
test('structured synthesis retry exhaustion recovers through bounded prose without rerunning peers',async()=>{let dispatches=0;const calls=[];const result=await deliberateEpisode({...options(),dispatch:async()=>{dispatches++;return peers;},runModel:async o=>{calls.push(o);return o.schema?{isError:true,errorSubtype:'error_max_structured_output_retries',costUsd:.02}:{text:'The regional survey does not establish the depth along that crossing. A charted profile is still needed.',costUsd:.01};}});assert.equal(result.ok,true);assert.equal(dispatches,1);assert.equal(calls.length,2);assert.equal(calls[1].schema,undefined);assert.deepEqual(calls[1].tools,[]);assert.ok(calls[1].timeoutMs<=120000);assert.equal(result.synthesisMode,'plain_text_recovery');assert.deepEqual(result.claims,[]);assert.equal(result.status,'model_prior');assert.ok(Math.abs(result.costUsd-.03)<1e-8);});
test('an errored model result cannot promote a structured answer to success',async()=>{const result=await deliberateEpisode({...options(),runModel:async()=>({isError:true,errorSubtype:'authentication_required',structured:{answer:'Untrusted completed-looking answer.',status:'verified'}})});assert.equal(result.ok,false);});
test('synthesis recovery never invents quorum or succeeds on empty fallback',async()=>{let calls=0;let r=await deliberateEpisode({...options(),dispatch:async()=>({...peers,reviewers:peers.reviewers.slice(0,1)}),runModel:async()=>{calls++;return {};}});assert.equal(r.ok,false);assert.equal(calls,0);r=await deliberateEpisode({...options(),runModel:async()=>({isError:true,errorSubtype:'error_max_structured_output_retries'})});assert.equal(r.ok,false);assert.equal(r.review.successes,2);});
test('try again retries the last review before an unrelated pending search offer',()=>{assert.equal(interactionCommand('Try again.').kind,'resume');assert.equal(interactionCommand('Retry the review.').kind,'review');const r=resolveDialogue('Try again.',{...createDialogueState(),lastOperation:{kind:'review',scope:'answer',target:'ep_recovery'},pendingAction:{kind:'research',subject:'A different search',status:'offered'},lastSubstantiveQuestion:'A different search'});assert.equal(r.route,'review');assert.equal(r.reviewTarget,'ep_recovery');});
test('compound both preserves the approved subject, jurisdiction and added question',()=>{const subject='Check the charted depth across the North Channel between Northern Ireland and Scotland',key='bound';const state={...createDialogueState(),lastSubstantiveQuestion:subject,lastSubstantiveTurn:{question:subject,semanticKey:key},lastCompletedKey:key,pendingAction:{kind:'research',subject,jurisdiction:'United Kingdom',researchMode:'live_sources',status:'offered',origin:{kind:'turn',semanticKey:key}}};const r=resolveDialogue('Do both of your suggestions and also explain the measurement uncertainty.',state);assert.equal(r.route,'research');assert.equal(r.reviewRequested,true);assert.equal(r.jurisdiction,'United Kingdom');assert.match(r.canonical,/North Channel/);assert.match(r.canonical,/measurement uncertainty/);assert.notEqual(resolveDialogue("Don't do both of your suggestions",state).reviewRequested,true);});
test('a performance follow-up does not become a new population-search subject',()=>{assert.equal(conversationRepairQuestion('What about now after your updates? Can you figure everything out?'),true);});
test('source discovery records observed WebSearch separately from candidate URLs',async()=>{for(const observed of [false,true]){const r=await runLiveTools({question:'North Channel charted depth',request:{name:'search_web'},budget:new LiveLookupBudget(),allowRecovery:false,runModel:async o=>{if(observed)o.onEvent?.({type:'assistant',message:{content:[{type:'tool_use',id:'tool_1',name:'WebSearch'}]}});return {structured:{urls:['https://example.org/chart']},webSearches:0};},get:async url=>({url,headers:{'content-type':'text/html'},body:'<p>A North Channel charted depth survey requires a continuous profile and its datum.</p>'})});const call=r.calls.find(c=>c.name==='search_web');assert.equal(call.searchExecution,observed?'observed':'unconfirmed');assert.equal(call.webSearches,observed?1:0);}});

import {KnowledgeBase} from '../lib/kb.mjs';import {ConversationStore} from '../lib/conversations.mjs';
const RecoveryStore=process.env.REVIEW_RECOVERY_BASELINE?(await import(process.env.REVIEW_RECOVERY_BASELINE)).ConversationStore:ConversationStore;
test('a saved misrouted retry recovers its server-recorded review target without running work',t=>{const kb=new KnowledgeBase(':memory:');t.after(()=>kb.close());const c=new RecoveryStore(kb.db);c.start({id:'old-review',sessionId:'s',question:'Use MOMM.',resolution:{route:'review',jurisdiction:'United Kingdom'}});c.finish('old-review',{answer:'Review accepted.',metadata:{action:{kind:'review_answer',target:'ep_original',serverStarted:true}}});c.start({id:'retry',sessionId:'s',question:'Try again.',resolution:{route:'answer',jurisdiction:'United Kingdom'}});c.finish('retry',{answer:'An unrelated lookup ran.'});c.saveState('s',{...createDialogueState(),lastOperation:{kind:'search'},lastSubstantiveQuestion:'Wrong diagnostic subject'});const before=JSON.stringify(c.page('s')),state=c.loadState('s'),r=resolveDialogue('Try again.',state);assert.equal(r.route,'review');assert.equal(r.reviewTarget,'ep_original');assert.equal(JSON.stringify(c.page('s')),before);c.start({id:'new',sessionId:'s',question:'Search Manx railway opening times',resolution:{route:'answer',jurisdiction:'United Kingdom'}});c.finish('new',{answer:'New topic.'});c.saveState('s',{...createDialogueState(),lastOperation:{kind:'search'},lastSubstantiveQuestion:'Manx railway opening times'});assert.notEqual(c.loadState('s').lastOperation.kind,'review');});
test('do both can bind an explicit source-and-review offer in the latest recap',t=>{const kb=new KnowledgeBase(':memory:');t.after(()=>kb.close());const c=new ConversationStore(kb.db);c.start({id:'recap',sessionId:'s',question:'Review our conversation',resolution:{route:'answer',jurisdiction:'United Kingdom'}});c.finish('recap',{answer:'I can search that missing depth and run a review of this conversation.',metadata:{meta:{intent:'recap',gaps:['charted depth along the Northern Ireland to Scotland crossing']}}});const raw='Do both of your suggestions and also explain measurement uncertainty.',previous=createDialogueState();const r=c.bindResearchFollowup('s',raw,resolveDialogue(raw,previous),previous);assert.equal(r.route,'research');assert.equal(r.reviewRequested,true);assert.equal(r.reviewScope,'conversation');assert.equal(r.jurisdiction,'United Kingdom');assert.match(r.canonical,/charted depth/);assert.match(r.canonical,/measurement uncertainty/);});
