import test from 'node:test';import assert from 'node:assert/strict';import {parallelDiscovery,parseSearchResults,searchQuery} from '../lib/search-discovery.mjs';import {runLiveTools,LiveLookupBudget} from '../lib/live-tools.mjs';import {persistPublicEvidence} from '../lib/evidence-ledger.mjs';import {KnowledgeBase} from '../lib/kb.mjs';
const robots={status:200,body:'User-agent: *\nAllow: /'};
const source='https://www.tynwald.org.im/history';
const rss={status:200,body:'<rss><channel><item><link>'+source+'</link></item><item><link>http://127.0.0.1/private</link></item></channel></rss>'};
const html={status:200,body:'<a class="result__a" href="//duckduckgo.com/l/?uddg='+encodeURIComponent(source)+'">History</a>'};
test('three discovery routes overlap, preserve partial results and deduplicate publisher provenance',async()=>{
 const started=new Set();let release;const barrier=new Promise(r=>release=r);const gate=async name=>{started.add(name);if(started.size===3)release();await barrier;};
 const r=await parallelDiscovery({question:'Isle of Man constitutional history',modelSearch:async()=>{await gate('model');throw Error('OAuth search timed out');},get:async url=>{const name=new URL(url).hostname;await gate(name);return url.endsWith('/robots.txt')?robots:name.includes('bing')?rss:html;}});
 assert.equal(started.size,3);assert.deepEqual(r.urls,[source]);assert.deepEqual(r.candidates[0].providers,['bing','duckduckgo']);assert.equal(r.routes[0].status,'unavailable');assert.equal(r.routes[1].rejectedCount,1);assert.equal(r.searchOutcome,'partial');assert.equal(r.costComplete,false);assert.equal(r.claims,undefined);
});
test('privacy guard prevents every external dispatch, including URL credentials and private IPs',async()=>{
 for(const question of ['My email is patient@example.com and my password is secret123','Read https://127.0.0.1/private','Read https://user:secret@example.com/history']){let calls=0;await assert.rejects(parallelDiscovery({question,modelSearch:async()=>{calls++;},get:async()=>{calls++;}}));assert.equal(calls,0);}
});
test('caller cancellation ends discovery even when a provider ignores abort',async()=>{const c=new AbortController();let started=0;const hang=async()=>{started++;if(started===3)c.abort(Error('User stopped'));return new Promise(()=>{});};await assert.rejects(parallelDiscovery({question:'Manx history',signal:c.signal,modelSearch:hang,get:hang}),/User stopped/);});
test('one timed out route does not discard accessible search results',async()=>{const r=await parallelDiscovery({question:'Manx history',modelTimeoutMs:10,modelSearch:()=>new Promise(()=>{}),get:async url=>url.endsWith('/robots.txt')?robots:url.includes('bing')?rss:html});assert.deepEqual(r.urls,[source]);assert.equal(r.routes[0].code,'search_route_timeout');});
test('challenge and malformed pages are failures, queries bounded and no redirect fetched',()=>{assert.throws(()=>parseSearchResults('duckduckgo',{status:200,body:'<form class="anomaly-modal">Solve</form>'}));assert.throws(()=>parseSearchResults('bing',{status:200,body:'<html>Search unavailable</html>'}));assert.ok(searchQuery('first '+ 'word '.repeat(100)+'last').length<=240);assert.match(searchQuery('first '+ 'word '.repeat(100)+'last'),/^first.*last$/);});
test('successful parallel search performs actual reads and only fetched excerpts enter the ledger',async t=>{
 const kb=new KnowledgeBase(':memory:');t.after(()=>kb.close());let reads=0;const events=[];
 const r=await runLiveTools({question:'Search Manx constitutional history',request:{name:'search_web'},parallelSearch:true,allowRecovery:false,budget:new LiveLookupBudget(),emit:(name,data)=>events.push({name,...data}),runModel:async()=>({isError:true,errorSubtype:'timeout'}),get:async url=>{if(url.endsWith('/robots.txt'))return robots;if(url.includes('bing.com'))return rss;if(url.includes('duckduckgo'))return html;reads++;return {url,headers:{'content-type':'text/html'},body:'<main><h1>Manx constitutional history</h1><p>Synthetic Manx constitutional history is recorded by this public institution.</p></main>'};}});
 assert.equal(reads,1);assert.equal(r.claims.length,1);assert.equal(r.calls.find(c=>c.name==='search_web').routes.length,3);assert.ok(events.some(e=>e.name==='search_bing'&&e.status==='working'));const receipt=persistPublicEvidence(kb,r,{question:'Manx constitutional history'});assert.equal(receipt.stored,1);assert.equal(kb.getClaim(receipt.ids[0]).support,1);assert.equal(kb.getClaim(receipt.ids[0]).sources.length,1);
 const discoveryOnly={...r,calls:r.calls.filter(c=>c.name==='search_web')};assert.equal(persistPublicEvidence(kb,discoveryOnly,{question:'Manx constitutional history'}).stored,0);
});

test('the aggregate deadline includes page reads and prevents recovery after exhaustion',async()=>{const began=Date.now();let reads=0;const r=await runLiveTools({question:'Search Manx constitutional history',request:{name:'search_web'},timeoutMs:25,allowRecovery:true,parallelSearch:false,budget:new LiveLookupBudget(),runModel:async()=>({structured:{urls:[source]}}),get:async(_url,{signal})=>{reads++;await new Promise((_,reject)=>{signal.addEventListener('abort',()=>reject(signal.reason),{once:true});});}});assert.equal(reads,1);assert.equal(r.claims.length,0);assert.equal(r.calls.at(-1).code,'lookup_deadline');assert.ok(Date.now()-began<2000);});
