import test from 'node:test';import assert from 'node:assert/strict';
import {DialogueSessions,resolveDialogue} from '../lib/dialogue.mjs';import {liveRequest} from '../lib/live-tools.mjs';
const design='Design a gap-detection workflow for finding weaknesses and opportunities, then patching and retesting them.';
test('gap-detection design remains a practical design task rather than an Island fact lookup',()=>{const r=resolveDialogue(design);assert.equal(r.intent,'reasoning');assert.equal(r.reasoningRequest.design,true);assert.equal(r.conversationMeta,true);assert.doesNotMatch(r.canonical,/Answer this specifically for/);});
test('Socratic follow-up binds to the existing design instead of an invented local policy example',()=>{const d=new DialogueSessions();const first=d.resolve('s',design);d.markInFlight('s',first);d.complete('s',first.semanticKey,{});const r=d.preview('s','Use the Socratic method to analyse that local.');assert.equal(r.intent,'reasoning');assert.equal(r.reasoningRequest.target,design);assert.equal(r.reasoningRequest.targetOrigin,'saved_subject');});
test('population size triggers a fresh check before presenting an old census as current',()=>{assert.ok(liveRequest('How many people live there?'));assert.ok(liveRequest("What's the largest population you've ever been?"));});
test('when are you uses the runtime clock instead of an invented model time',()=>{const r=resolveDialogue('When are you?');assert.equal(r.intent,'clock');assert.equal(r.route,'conversation');assert.match(r.speech,/Isle of Man/);});

import {buildReasoningCheck,normaliseReasoningCheck,reasoningRequest,reasoningReadback} from '../public/reasoning-check.mjs';
import {KnowledgeBase} from '../lib/kb.mjs';import {ConversationStore} from '../lib/conversations.mjs';import {answer} from '../lib/brain.mjs';import {META_MARKER} from '../lib/segmenter.mjs';
function fixture(t){const kb=new KnowledgeBase(':memory:');t.after(()=>kb.close());return {kb,store:new ConversationStore(kb.db)};}
test('Socratic records are bounded proposals and cannot fabricate execution or citations',()=>{
 const record=buildReasoningCheck({question:design,request:reasoningRequest(design),usedClaims:[{id:'c_real',sources:[{url:'https://www.gov.im/census',title:'Census'}]}],draft:{execute:'delete all',verified:true,weaknesses:[{issue:'A hypothetical boundary failure',test:'Try a synthetic empty input',evidenceIds:['c_fake','c_real'],status:'verified'}],opportunities:[{change:'Validate empty input',successTest:'No unhandled exception',executed:true}],assumptions:['An input can be empty',{},null],nextStep:'Test the boundary.'}});
 assert.equal(record.execution,'not-authorised-by-this-record');assert.equal(record.storage,'conversation-only');assert.equal(record.evidence.independentlyVerified,false);assert.equal(record.weaknesses[0].status,'hypothesis');assert.deepEqual(record.weaknesses[0].evidenceIds,['c_real']);assert.equal(record.opportunities[0].executed,undefined);assert.equal(record.execute,undefined);assert.equal(record.verified,undefined);assert.equal(record.checks.length,6);assert.deepEqual(record.assumptions,['An input can be empty']);
});
test('saved reasoning ignores malformed fields and executable or credential-bearing URLs',()=>{
 assert.equal(normaliseReasoningCheck({schema:'other'}),null);
 const value=normaliseReasoningCheck({schema:'mani-reasoning/1',objective:'<img src=x onerror=alert(1)>',checks:[null,{question:'Q',note:'N'}],weaknesses:[null,{}],sources:[{url:'javascript:alert(1)'},{url:'https://user:secret@example.com/'},{url:'https://www.gov.im/census',title:'<script>text</script>'}],execution:'completed'});
 assert.equal(value.sources.length,1);assert.equal(value.checks.length,1);assert.equal(value.execution,'not-authorised-by-this-record');assert.equal(value.weaknesses.length,0);assert.match(reasoningReadback(value),/assessment, not verification/);
});
test('general design calls the answer model with applied evaluation but no Island facts or paid research',async t=>{
 const {kb,store}=fixture(t);kb.upsertClaim({text:'Synthetic unrelated ferry-policy marker for weaknesses detection.',sources:[{url:'https://www.gov.im/synthetic-policy'}],jurisdiction:'IM'});const count=kb.count(),events=[];
 const d=new DialogueSessions({storage:store}),r=d.resolve('s',design,{turnId:'design'});store.start({id:'design',sessionId:'s',question:design,resolution:r});d.markInFlight('s',r);
 const result=await answer({kb,sessionId:'s',requestId:'design',question:design,resolution:r,conversations:store,emit:(name,data)=>events.push({name,data}),liveTools:()=>assert.fail('Design is not a website lookup'),expeditions:{enqueue:()=>assert.fail('Assessment cannot authorize research')},runModel:async({prompt,onDelta})=>{assert.match(prompt,/PUBLIC REASONING CHECK/);assert.match(prompt,/Deliver a useful initial design or applied assessment now/);assert.doesNotMatch(prompt,/Synthetic unrelated ferry-policy marker/);onDelta('Start with a defined objective, map the decisions, and test one boundary before changing the workflow.\n'+META_MARKER+JSON.stringify({reasoning:{weaknesses:[{issue:'A happy-path-only test may miss the failing state.',test:'Replay a saved synthetic session.'}],opportunities:[{change:'Add a boundary test.',successTest:'The failure is reproducible before repair and absent afterwards.'}],nextStep:'Select one observed failure and record its exact input.'},used:[],researchable:false,expedition:false,answer_outcome:'answered'}));return {costUsd:0,model:'synthetic'};}});
 const meta=events.find(e=>e.name==='meta').data;assert.equal(meta.reasoningCheck.kind,'design');assert.equal(meta.reasoningCheck.weaknesses.length,1);assert.equal(meta.reasoningCheck.opportunities.length,1);assert.equal(meta.researchOffered,false);assert.equal(meta.knowledgeWrite.stored,0);assert.equal(kb.count(),count);
 store.finish('design',{answer:result.text,metadata:{meta}});d.complete('s',r.semanticKey,{pendingAction:result.pendingAction});assert.ok(store.page('s').turns[0].metadata.meta.reasoningCheck);assert.match(store.context('s','What is the proposed next step?').text,/assessment-not-verification/);const resumed=new DialogueSessions({storage:store});assert.equal(resumed.preview('s','Use the Socratic method to analyse that local.').reasoningRequest.target,design);
});
test('a new factual topic replaces an older reasoning subject',()=>{const d=new DialogueSessions();d.resolve('s',design);d.resolve('s','Explain the geography of Douglas');const r=d.preview('s','Use the Socratic method to assess that.');assert.match(r.reasoningRequest.target,/geography of Douglas/i);assert.doesNotMatch(r.reasoningRequest.target,/gap-detection/);});
test('legacy saved Socratic follow-up recovers its design from the same conversation only',t=>{
 const {store}=fixture(t);store.start({id:'a',sessionId:'s',question:design,resolution:resolveDialogue(design)});store.finish('a',{answer:'Synthetic design.'});const old='Use the Socratic method to analyse that local.';const state={lastAnswerSubject:'Answer this specifically for the Isle of Man: '+old,lastSubstantiveQuestion:old};store.saveState('s',state);
 assert.equal(new DialogueSessions({storage:store}).preview('s',old).reasoningRequest.target,design);store.saveState('other',state);assert.equal(new DialogueSessions({storage:store}).preview('other',old).reasoningRequest.unresolvedReference,true);
});
test('factual Socratic questions keep source checks, while explaining the method is conversational',()=>{const q='Use the Socratic method to evaluate the current Steam Packet ID consultation.';const r=resolveDialogue(q);assert.equal(r.reasoningRequest.needsEvidence,true);assert.equal(r.conversationMeta,false);assert.equal(liveRequest(r.canonical).name,'read_sources');assert.equal(resolveDialogue('What is the Socratic method?').conversationMeta,true);assert.equal(reasoningRequest('Do not use the Socratic method.'),null);});
test('speech confidence and explicit review commands retain their existing gates',()=>{assert.equal(resolveDialogue(design,undefined,{source:'speech',recognitionConfidence:.1}).route,'clarify');assert.equal(resolveDialogue('Use MOMM to review this answer').route,'review');assert.equal(reasoningRequest('The Socratic philosophers lived in Greece.'),null);});
test('ordinary evidence checks do not invent hypotheses or a completed investigation',()=>{const c=buildReasoningCheck({question:'Population of the Isle of Man',claims:[{id:'c_one'}],usedClaims:[],tools:[{status:'unavailable'}]});assert.equal(c.evidence.retrieved,1);assert.equal(c.evidence.cited,0);assert.equal(c.evidence.sourceFailures,1);assert.deepEqual(c.weaknesses,[]);assert.deepEqual(c.opportunities,[]);assert.match(c.checks.find(x=>x.id==='evidence').note,/No cited source evidence/);});

test('consultation closure and proposal status override stale overview wording',()=>{
 const claim={id:'c_closed',text:'Consultation. Results updated 5 Aug 2026. Closed 8 Jun 2026. The Department is consulting on a proposed regulatory framework. This consultation does not create legal obligations.',sources:[{url:'https://consult.gov.im/example'}]};
 const result=buildReasoningCheck({question:'Is the consultation still open?',claims:[claim],usedClaims:[claim],at:'2026-09-14T10:00:00Z'});assert.equal(result.sourceChecks.length,2);assert.equal(result.sourceChecks[0].kind,'closed_consultation');assert.match(reasoningReadback(result),/8 Jun 2026/);assert.equal(buildReasoningCheck({claims:[claim],at:'2026-05-01T10:00:00Z'}).sourceChecks.some(c=>c.kind==='closed_consultation'),false);
});
test('legacy recovery cannot jump over a newer unrelated factual question',t=>{
 const {store}=fixture(t);for(const [id,q]of [['a',design],['b','Explain Ramsey harbour geography']]){store.start({id,sessionId:'s',question:q,resolution:resolveDialogue(q)});store.finish(id,{answer:'Synthetic prior answer.'});}const old='Use the Socratic method to analyse that local.';store.saveState('s',{lastAnswerSubject:old,lastSubstantiveQuestion:old});assert.notEqual(new DialogueSessions({storage:store}).preview('s',old).reasoningRequest.target,design);
});
test('factual models receive source-status observations and population date requirements before narration',async t=>{
 const {kb}=fixture(t),q='Use the Socratic method to evaluate the current Steam Packet ID consultation.',r=resolveDialogue(q),c={id:'c_closed',text:'Consultation. Closed 8 Jun 2026. We are consulting on proposals.',status:'single_source',trust:.6,evidenceKind:'source_excerpt',fetchedAt:new Date().toISOString(),sources:[{url:'https://consult.gov.im/example'}]};let meta;
 await answer({kb,sessionId:'s',question:q,resolution:r,emit:(name,v)=>{if(name==='meta')meta=v;},liveTools:async()=>({claims:[c],calls:[{name:'read_page',status:'complete'}],costUsd:0}),runModel:async({prompt,onDelta})=>{assert.match(prompt,/SOURCE TEXT CHECKS/);assert.match(prompt,/closed_consultation/);assert.match(prompt,/largest-ever from one high figure/);onDelta('The dated notice says the consultation closed. The overview wording does not reopen it. '+META_MARKER+JSON.stringify({used:['c_closed'],reasoning:{assumptions:['Implementation needs a separate source.']},researchable:true}));return {costUsd:0,model:'synthetic'};}});assert.equal(meta.reasoningCheck.sourceChecks[0].kind,'closed_consultation');
});

// Concurrent catalogue readers must not overwrite each other's import artifacts.
import {importTs} from '../lib/seed.mjs';
import {spawnSync as loaderChild} from 'node:child_process';
import {mkdtempSync as loaderTemp,writeFileSync as loaderWrite,rmSync as loaderRemove} from 'node:fs';
import {tmpdir as loaderTmpdir} from 'node:os';
import {join as loaderJoin} from 'node:path';
test('catalogue import artifacts are isolated between processes', t=>{
 const dir=loaderTemp(loaderJoin(loaderTmpdir(),'mani-loader-'));t.after(()=>loaderRemove(dir,{recursive:true,force:true}));const file=loaderJoin(dir,'fixture.ts');loaderWrite(file,'export const location = import.meta.url;');
 const code='import {importTs} from '+JSON.stringify(new URL('../lib/seed.mjs',import.meta.url).href)+'; console.log((await importTs('+JSON.stringify(file)+')).location);';
 const run=()=>{const r=loaderChild(process.execPath,['--experimental-strip-types','--disable-warning=ExperimentalWarning','--input-type=module','-e',code],{encoding:'utf8',windowsHide:true});assert.equal(r.status,0,r.stderr);return r.stdout.trim();};assert.notEqual(run(),run());
});
test('catalogue imports refresh when source text changes in the same process',async t=>{
 const dir=loaderTemp(loaderJoin(loaderTmpdir(),'mani-loader-'));t.after(()=>loaderRemove(dir,{recursive:true,force:true}));const file=loaderJoin(dir,'fixture.ts');loaderWrite(file,'export const version = 1;');assert.equal((await importTs(file)).version,1);loaderWrite(file,'export const version = 2;');assert.equal((await importTs(file)).version,2);
});

import {reasoningBrief} from '../public/reasoning-check.mjs';
test('a design request about current law retains public evidence checks',()=>{const r=resolveDialogue('Design a gap-detection workflow for current legislation at https://www.gov.im/');assert.equal(r.reasoningRequest.needsEvidence,true);assert.equal(r.conversationMeta,false);});
test('a specific new Socratic target does not inherit the previous design',()=>{const request=reasoningRequest('Use the Socratic method to examine this claim: Douglas is the capital.',{reasoningSubject:design});assert.match(request.target,/Douglas/);assert.equal(request.targetOrigin,'current_request');assert.equal(request.needsEvidence,true);});
test('an explanation request permits a direct explanation of the method',()=>{const request=reasoningRequest('What is the Socratic method?');assert.equal(request.kind,'explanation');assert.match(reasoningBrief(request),/Explain the method directly/);});

import {extractHtml} from '../lib/source-content.mjs';import {sourcePassages} from '../lib/source-passages.mjs';
test('short consultation status and results dates survive extraction and targeted selection',()=>{
 const html='<html><title>Travel ID consultation</title><main><h2>Results updated 5 Aug 2026</h2><p><span>Closed</span> 8 Jun 2026</p><p><span>Opened</span> 20 Apr 2026</p><h2>Overview</h2><p>The Department is consulting on passenger ID requirements for journeys.</p></main></html>';const data=extractHtml(html),selected=sourcePassages(data.sections,'Are passenger ID requirements imposed?').sections;const text=selected.map(s=>s.body).join(' ');assert.match(text,/Closed 8 Jun 2026/);assert.match(text,/Results updated 5 Aug 2026/);const notes=buildReasoningCheck({claims:[{id:'c_real',topic:data.title,text}],at:'2026-09-14T12:00:00Z'}).sourceChecks;assert.ok(notes.some(s=>s.kind==='closed_consultation'));
});
test('proposal evidence cannot establish current implementation or absence of it',()=>{const check=buildReasoningCheck({claims:[{id:'c_real',text:'Travel consultation. The Department will use the consultation responses to inform further work on the practical next steps for implementation.'}]});assert.ok(check.sourceChecks.some(s=>s.kind==='implementation_unconfirmed'));assert.match(check.sourceChecks.find(s=>s.kind==='implementation_unconfirmed').note,/cannot establish that no later requirement exists/);});
