import test from 'node:test';import assert from 'node:assert/strict';
import {resolveDialogue,createDialogueState,DialogueSessions} from '../lib/dialogue.mjs';
import {KnowledgeBase} from '../lib/kb.mjs';import {ConversationStore} from '../lib/conversations.mjs';import {answer} from '../lib/brain.mjs';import {liveRequest,runLiveTools} from '../lib/live-tools.mjs';import {WEATHER_PLACES} from '../lib/town-weather.mjs';
const question="What's the temperature today in all the major towns?";
const correction='I asked what was the temperature in all the major towns.';
const oldMenu='We’re focused on the Isle of Man. Do you want its infrastructure, companies and law, government, geography, or a full island overview?';
test('all main towns is an explicit weather request within the default jurisdiction',()=>{const r=resolveDialogue(question);assert.equal(r.route,'answer');assert.equal(r.jurisdiction,'Isle of Man');assert.equal(liveRequest(r.canonical).name,'get_town_weather');assert.equal(liveRequest(r.canonical).places.length,8);});
test('a quantified new subject replaces the previous infrastructure topic',()=>{const prior=resolveDialogue('Tell me about infrastructure').state;for(const q of [question,'What are all the work permit requirements?','Tell me about all the towns','List all current school closures']){const r=resolveDialogue(q,prior);assert.equal(r.route,'answer');assert.match(r.canonical,new RegExp(q.includes('temperature')?'temperature':q.includes('permit')?'permit':q.includes('school')?'school':'towns','i'));assert.doesNotMatch(r.canonical,/infrastructure/i);}});
test('a complete quantified question is not turned into an Island overview',()=>{for(const q of ['List all Isle of Man towns','Explain everything about Manx company registration','Give me complete information about work permits']){const r=resolveDialogue(q);assert.equal(r.route,'answer');assert.match(r.canonical,new RegExp(q.includes('towns')?'towns':q.includes('registration')?'registration':'permits','i'));}});
test('a reported-question correction inherits the current time frame of its weather question',()=>{const prior={...createDialogueState(),lastSubstantiveQuestion:'Answer this specifically for the Isle of Man: '+question};const r=resolveDialogue(correction,prior);assert.equal(r.raw,correction);assert.equal(liveRequest(r.canonical)?.name,'get_town_weather');assert.doesNotMatch(r.canonical,/\bwas\b/i);});
test('restating an explicitly historical question does not turn it into current weather',()=>{const prior={...createDialogueState(),lastSubstantiveQuestion:question};const r=resolveDialogue('I asked what was the temperature yesterday in all the major towns.',prior);assert.match(r.canonical,/yesterday/);assert.notEqual(liveRequest(r.canonical)?.name,'get_town_weather');});
test('standalone broadening, foreign scope and uncertain speech keep their boundaries',()=>{const prior=resolveDialogue('Tell me about infrastructure').state;assert.match(resolveDialogue('all',prior).canonical,/infrastructure/);assert.equal(resolveDialogue('all').route,'clarify');assert.equal(resolveDialogue('What are all the towns in Jersey?',prior).jurisdiction,'Jersey');assert.equal(resolveDialogue(question,undefined,{source:'speech',recognitionConfidence:.2}).route,'clarify');});
test('legacy false clarification recovers its factual subject without changing recorded answers',t=>{const kb=new KnowledgeBase(':memory:');t.after(()=>kb.close());const store=new ConversationStore(kb.db);store.start({id:'old',sessionId:'s',question,resolution:{route:'clarify',jurisdiction:'Isle of Man'}});store.finish('old',{answer:oldMenu,metadata:{meta:{mode:'clarify',answered:true}}});store.saveState('s',{...createDialogueState(),lastOperation:{kind:'review',scope:'conversation'},customPreference:'preserve'});const before=store.page('s').turns[0];const d=new DialogueSessions({storage:store});const r=d.preview('s',correction);assert.equal(liveRequest(r.canonical)?.name,'get_town_weather');assert.equal(store.loadState('s').customPreference,'preserve');assert.deepEqual(store.page('s').turns[0],before);assert.equal(store.loadState('other'),null);});
test('legacy recovery does not reuse a declined question across a newer factual task',t=>{const kb=new KnowledgeBase(':memory:');t.after(()=>kb.close());const store=new ConversationStore(kb.db);store.start({id:'old',sessionId:'s',question,resolution:{route:'clarify',jurisdiction:'Isle of Man'}});store.finish('old',{answer:oldMenu});const latest=resolveDialogue('What is the capital of Jersey?');store.start({id:'new',sessionId:'s',question:latest.raw,resolution:latest});store.finish('new',{answer:'Synthetic answer.'});store.saveState('s',createDialogueState());assert.equal(store.loadState('s').lastSubstantiveQuestion,null);});
test('a clarification is not marked as a completed answer',async()=>{const events=[];await answer({question:'all',resolution:resolveDialogue('all'),emit:(name,data)=>events.push({name,data})});const meta=events.find(e=>e.name==='meta').data;assert.equal(meta.answered,false);assert.equal(meta.answerOutcome,'clarification_required');assert.equal(meta.costUsd,0);});
test('explicit conversation review remains an intentional review operation',()=>{const r=resolveDialogue("Review the conversation. If we're focused on the Isle of Man, then surely I was asking about the Isle of Man. Then you refused to answer.");assert.equal(r.route,'review');assert.equal(r.reviewScope,'conversation');});
test('the full weather and correction exchange reads all configured places and writes only source evidence',async t=>{const kb=new KnowledgeBase(':memory:');t.after(()=>kb.close());const d=new DialogueSessions();let reads=0;for(const q of [question,correction]){const resolution=d.resolve('s',q),events=[];assert.equal(resolution.route,'answer');d.markInFlight('s',resolution);const at=new Date(),rows=WEATHER_PLACES.map((p,i)=>({latitude:p.lat,longitude:p.lon,current_units:{temperature_2m:'°C',time:'unixtime'},current:{temperature_2m:11+i,time:Math.floor(at.getTime()/1000)}}));const result=await answer({kb,question:q,resolution,sessionId:'s',emit:(name,data)=>events.push({name,data}),liveTools:o=>runLiveTools({...o,at,useCache:false,allowRecovery:false,get:async url=>{reads++;assert.match(url,/api\.open-meteo\.com/);return {url,body:JSON.stringify(rows),headers:{'content-type':'application/json'},fetchedAt:at.toISOString()};}}),runModel:()=>{throw Error('A complete temperature tool result must not require model synthesis');}});const meta=events.find(e=>e.name==='meta').data;assert.equal(meta.answered,true);assert.equal(meta.knowledgeWrite.stored,8);assert.equal(meta.entailmentNotice,'');assert.equal(meta.status,'single_source');for(const p of WEATHER_PLACES)assert.match(result.text,new RegExp(p.name));assert.match(result.text,/model estimates, not thermometer measurements/i);d.complete('s',resolution.semanticKey,{});}assert.equal(reads,2);});

test('an explicit clock time or changed location in a reported question is not inherited as current',()=>{const prior={...createDialogueState(),lastSubstantiveQuestion:question};for(const q of ['I asked what was the temperature in all the major towns at 10am.','I asked what was the temperature in all the major towns two hours earlier.','I asked what was the temperature in Douglas.']){const r=resolveDialogue(q,prior);assert.match(r.canonical,/\bwas\b/i);assert.notEqual(liveRequest(r.canonical)?.name,'get_town_weather');}});

import {parseTownWeather} from '../lib/town-weather.mjs';import {META_MARKER} from '../lib/segmenter.mjs';
test('an unsupported explicitly named locality never falls back to an airport reading',()=>{for(const q of ['Current temperature in Jurby','Current temperature in Glen Maye','Current weather in Santon'])assert.equal(liveRequest(q)?.name,'search_web');});
test('an aggregate temperature result explicitly discloses its bounded place coverage',()=>{const at=new Date();const rows=WEATHER_PLACES.map(p=>({latitude:p.lat,longitude:p.lon,current_units:{temperature_2m:'°C',time:'unixtime'},current:{temperature_2m:14,time:Math.floor(at.getTime()/1000)}}));assert.match(parseTownWeather(JSON.stringify(rows),WEATHER_PLACES,at).text,/Coverage is limited to the eight places listed/);});
test('old or future weather cannot be presented as a current model estimate',()=>{const at=new Date();for(const delta of [-3*3600000,10*60000]){const p=WEATHER_PLACES[0],row={latitude:p.lat,longitude:p.lon,current_units:{temperature_2m:'°C',time:'unixtime'},current:{temperature_2m:14,time:Math.floor((at.getTime()+delta)/1000)}};assert.throws(()=>parseTownWeather(JSON.stringify(row),[p],at),/No fresh/);}assert.notEqual(liveRequest('Temperature in Douglas tomorrow')?.name,'get_town_weather');});
test('a correction and failed weather read add no speculation to factual knowledge',async t=>{const kb=new KnowledgeBase(':memory:');t.after(()=>kb.close());const events=[],prior={...createDialogueState(),lastSubstantiveQuestion:question},resolution=resolveDialogue(correction,prior);await answer({kb,question:correction,resolution,sessionId:'s',emit:(name,data)=>events.push({name,data}),liveTools:o=>runLiveTools({...o,useCache:false,allowRecovery:false,get:async()=>{throw Error('Synthetic unavailable source');}}),runModel:async o=>{o.onDelta('The temperature source could not be read.\n'+META_MARKER+JSON.stringify({used:[],answer_outcome:'insufficient_evidence',researchable:false}));return {costUsd:0};}});const meta=events.find(e=>e.name==='meta').data;assert.equal(meta.knowledgeWrite.stored,0);assert.equal(kb.count(),0);assert.equal(meta.answered,false);});

import {entailmentCheck,boundStatusByEntailment} from '../lib/entailment.mjs';
test('source timestamp formatting and hyphenated provider names do not create false unsupported facts',()=>{
 const claims=[{text:'Open-Meteo model estimate for Douglas: 18 degrees Celsius, valid at 2026-09-14T12:15:00.000Z. This is a model estimate, not a local thermometer observation.'}];
 const text='Open-Meteo model estimates: Douglas, 18 degrees Celsius at 2026-09-14 12:15 UTC.';
 const checked=entailmentCheck({answer:text,claims});assert.deepEqual(checked.unsupported,[]);assert.equal(boundStatusByEntailment('single_source',checked),'single_source');
 for(const [from,to,unsupported]of [['18 degrees','28 degrees','28'],['2026-09-14','2026-09-24','24'],['12:15','22:15','22'],['Open-Meteo','Other-Provider','Other-Provider'],['Douglas','Ramsey','Ramsey']])assert.ok(entailmentCheck({answer:text.replace(from,to),claims}).unsupported.includes(unsupported),unsupported);
});
